import json
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "KlondaikTweaker", "Assets", "Data", "software.json")
SITE = "https://klondaik.uk"

ITEMS = [
    ("everything", "Everything", "Files", "voidtools.Everything", True,
     "Мгновенный поиск файлов по всему диску. Находит за доли секунды то, что проводник ищет минуту.",
     "Instant file search across the whole drive."),
    ("7zip", "7-Zip", "Files", "7zip.7zip", True,
     "Лёгкий архиватор с высокой степенью сжатия. Открывает всё, что вообще бывает.",
     "Lightweight archiver with high compression. Opens everything."),
    ("sharex", "ShareX", "Media", "ShareX.ShareX", True,
     "Скриншоты и запись экрана с редактором и загрузкой на хостинги. Открытый код.",
     "Screenshots and screen recording with an editor and uploads. Open source."),
    ("localsend", "LocalSend", "Files", "LocalSend.LocalSend", True,
     "Открытая замена AirDrop: файлы между устройствами по локальной сети без интернета.",
     "Open-source AirDrop alternative over the local network."),
    ("vlc", "VLC", "Media", "VideoLAN.VLC", False,
     "Играет любое видео и аудио без установки кодеков.",
     "Plays any video and audio without extra codecs."),
    ("qbittorrent", "qBittorrent", "Files", "qBittorrent.qBittorrent", False,
     "Чистый торрент-клиент без рекламы и телеметрии.",
     "Clean torrent client with no ads or telemetry."),
    ("syncthing", "Syncthing", "Files", "Syncthing.Syncthing", False,
     "Децентрализованная синхронизация папок между устройствами без облака.",
     "Decentralised folder sync between devices, no cloud."),
    ("hwinfo", "HWiNFO64", "Monitoring", "REALiX.HWiNFO", False,
     "Полный мониторинг температур, частот и напряжений в реальном времени.",
     "Full real-time monitoring of temperatures, clocks and voltages."),
    ("gpuz", "GPU-Z", "Monitoring", "TechPowerUp.GPU-Z", False,
     "Вся информация о видеокарте и её датчиках.",
     "Everything about the GPU and its sensors."),
    ("cpuz", "CPU-Z", "Monitoring", "CPUID.CPU-Z", False,
     "Стандарт диагностики процессора, памяти и материнской платы.",
     "The standard for CPU, RAM and motherboard diagnostics."),
    ("afterburner", "MSI Afterburner", "Monitoring", "Guru3D.Afterburner", False,
     "Разгон, андервольт и игровой оверлей для видеокарт любых производителей.",
     "Overclocking, undervolting and an in-game overlay for any GPU."),
    ("crystaldiskinfo", "CrystalDiskInfo", "Storage", "CrystalDewWorld.CrystalDiskInfo", False,
     "Состояние дисков по данным S.M.A.R.T. Предупредит о смерти накопителя заранее.",
     "Drive health from S.M.A.R.T. data. Warns before a drive dies."),
    ("crystaldiskmark", "CrystalDiskMark", "Storage", "CrystalDewWorld.CrystalDiskMark", False,
     "Тест реальной скорости чтения и записи накопителя.",
     "Real sequential and random drive speed test."),
    ("wiztree", "WizTree", "Storage", "AntibodySoftware.WizTree", False,
     "Показывает, чем забит диск, за секунды — читает таблицу MFT напрямую.",
     "Shows what fills the disk in seconds by reading the MFT directly."),
    ("czkawka", "Czkawka", "Cleanup", "qarmin.czkawka", False,
     "Поиск дубликатов файлов, похожих фото и пустых папок. Быстрее аналогов.",
     "Finds duplicate files, similar photos and empty folders. Faster than the rest."),
    ("bleachbit", "BleachBit", "Cleanup", "BleachBit.BleachBit", True,
     "Очистка кэшей, логов и следов работы с открытым исходным кодом.",
     "Open-source cleaner for caches, logs and traces."),
    ("revo", "Revo Uninstaller", "Cleanup", "RevoUninstaller.RevoUninstaller", False,
     "Удаляет программы подчистую вместе с ключами реестра и остатками файлов.",
     "Removes programs completely, including registry keys and leftovers."),
    ("unchecky", "Unchecky", "Cleanup", "Unchecky.Unchecky", False,
     "Автоматически снимает галочки с попутного софта в установщиках.",
     "Automatically unchecks bundled software in installers."),
    ("autoruns", "Autoruns", "Startup", "Microsoft.Sysinternals.Autoruns", False,
     "Полный список всего, что стартует вместе с Windows. Инструмент Sysinternals.",
     "The complete list of everything that starts with Windows."),
    ("procexp", "Process Explorer", "Tools", "Microsoft.Sysinternals.ProcessExplorer", False,
     "Диспетчер задач, который показывает, что на самом деле происходит в системе.",
     "The task manager that actually shows what is going on."),
    ("proclasso", "Process Lasso", "Optimization", "BitSum.ProcessLasso", False,
     "ProBalance динамически снижает приоритет фоновых процессов и убирает подвисания.",
     "ProBalance lowers background process priority and removes hitching."),
    ("quickcpu", "Quick CPU", "Optimization", "CoderBag.QuickCPU", False,
     "Тонкая настройка парковки ядер и состояний энергосбережения процессора.",
     "Fine control over core parking and CPU power states."),
    ("memreduct", "Mem Reduct", "Optimization", "HenryPP.MemReduct", False,
     "Лёгкий монитор и очистка оперативной памяти в трее.",
     "Lightweight RAM monitor and cleaner in the tray."),
    ("throttlestop", "ThrottleStop", "Optimization", "TechPowerUp.ThrottleStop", False,
     "Снятие троттлинга и андервольт процессора на ноутбуках Intel.",
     "Removes throttling and undervolts Intel laptop CPUs."),
    ("optimizer", "Optimizer", "Optimization", "hellzerg.optimizer", False,
     "Набор твиков приватности и производительности с откатом.",
     "A set of privacy and performance tweaks with rollback."),
    ("nvcleanstall", "NVCleanstall", "Privacy", "TechPowerUp.NVCleanstall", False,
     "Установка драйвера NVIDIA без телеметрии и лишних компонентов.",
     "Installs the NVIDIA driver without telemetry or extras."),
    ("shutup10", "O&O ShutUp10++", "Privacy", "OO-Software.ShutUp10", False,
     "Панель управления всеми настройками приватности Windows в одном окне.",
     "All Windows privacy settings in a single window."),
    ("thisiswin11", "ThisIsWin11", "Interface", "builtbybel.ThisIsWin11", False,
     "Удаление встроенного мусора и настройка Windows 11 в одном интерфейсе.",
     "Debloat and configure Windows 11 from one interface."),
    ("taskbartweaker", "7+ Taskbar Tweaker", "Interface", "RaMMicHaeL.7-TaskbarTweaker", False,
     "Тонкая настройка поведения панели задач: группировка, клики, средняя кнопка.",
     "Fine-grained taskbar behaviour: grouping, clicks, middle button."),
    ("quicklook", "QuickLook", "Interface", "QL-Win.QuickLook", False,
     "Пробел в проводнике открывает предпросмотр файла, как в macOS.",
     "Space in Explorer previews the file, like macOS."),
    ("twinkletray", "Twinkle Tray", "Interface", "xanderfrangos.twinkletray", False,
     "Яркость внешних мониторов из трея по DDC/CI.",
     "External monitor brightness from the tray over DDC/CI."),
    ("superf4", "Super F4", "Interface", "StefanSundin.Superf4", False,
     "Ctrl+Alt+F4 мгновенно убивает зависшее окно, минуя диалог закрытия.",
     "Ctrl+Alt+F4 instantly kills a hung window."),
    ("eartrumpet", "EarTrumpet", "Media", "File-New-Project.EarTrumpet", False,
     "Микшер громкости по приложениям прямо в трее.",
     "Per-app volume mixer right in the tray."),
    ("losslesscut", "LosslessCut", "Media", "mifi.lossless-cut", False,
     "Режет и склеивает видео без перекодирования — секунды вместо часов.",
     "Cuts and joins video without re-encoding — seconds instead of hours."),
    ("snipaste", "Snipaste", "Media", "Liulien.Snipaste", False,
     "Скриншот, который можно приколоть поверх всех окон отдельным окошком.",
     "A screenshot you can pin on top of every window."),
    ("obs", "OBS Studio", "Media", "OBSProject.OBSStudio", False,
     "Запись экрана и стриминг. Стандарт индустрии, открытый код.",
     "Screen recording and streaming. The industry standard, open source."),
    ("playnite", "Playnite", "Gaming", "Playnite.Playnite", False,
     "Одна библиотека вместо семи лаунчеров: Steam, Epic, GOG, эмуляторы.",
     "One library instead of seven launchers: Steam, Epic, GOG, emulators."),
    ("scrcpy", "scrcpy", "Tools", "Genymobile.scrcpy", False,
     "Экран телефона на компьютере с управлением мышью и клавиатурой.",
     "Your phone screen on the PC with mouse and keyboard control."),
    ("ventoy", "Ventoy", "Tools", "Ventoy.Ventoy", False,
     "Одна флешка на все образы: ISO просто копируются на неё файлами.",
     "One USB stick for every image: ISOs are simply copied to it."),
    ("rufus", "Rufus", "Tools", "Rufus.Rufus", False,
     "Быстрое создание загрузочных флешек из образа.",
     "Fast bootable USB creation from an image."),
    ("vscode", "Visual Studio Code", "Tools", "Microsoft.VisualStudioCode", False,
     "Редактор кода с тысячами расширений, Git и отладчиком.",
     "Code editor with thousands of extensions, Git and a debugger."),
    ("bulkrename", "Bulk Rename Utility", "Files", "TGRMNSoftware.BulkRenameUtility", False,
     "Массовое переименование по шаблонам, регуляркам, дате и метаданным.",
     "Bulk renaming by patterns, regex, date and metadata."),
    ("regorganizer", "Reg Organizer", "Cleanup", "ChemTable.RegOrganizer", False,
     "Очистка реестра, полное удаление программ и оптимизация загрузки.",
     "Registry cleanup, full uninstall and boot optimisation."),
    ("malwarebytes", "Malwarebytes", "Security", "Malwarebytes.Malwarebytes", False,
     "Защита от вредоносных сайтов, майнеров и мошеннических страниц.",
     "Protection from malicious sites, miners and scam pages."),
    ("protonvpn", "ProtonVPN", "VPN", "Proton.ProtonVPN", True,
     "Бесплатный VPN без лимита трафика, швейцарская юрисдикция, открытый код.",
     "Free VPN with no traffic limit, Swiss jurisdiction, open source."),
    ("mullvad", "Mullvad VPN", "VPN", "MullvadVPN.MullvadVPN", True,
     "Максимальная анонимность: для регистрации не нужен даже email.",
     "Maximum anonymity: registration does not even need an email."),
    ("amnezia", "AmneziaVPN", "VPN", "AmneziaVPN.AmneziaVPN", True,
     "Свой VPN на арендованном сервере за пару кликов. Обходит блокировки.",
     "Your own VPN on a rented server in a couple of clicks."),
    ("powertoys", "PowerToys", "Tools", "Microsoft.PowerToys", False,
     "Набор утилит от Microsoft: FancyZones, PowerRename, Run, Text Extractor.",
     "Microsoft's utility set: FancyZones, PowerRename, Run, Text Extractor."),
    ("notepadpp", "Notepad++", "Tools", "Notepad++.Notepad++", False,
     "Быстрый текстовый редактор с подсветкой синтаксиса.",
     "Fast text editor with syntax highlighting."),
    ("firefox", "Firefox", "Tools", "Mozilla.Firefox", False,
     "Браузер с независимым движком и настоящей защитой от слежки.",
     "Browser with an independent engine and real tracking protection."),
]

NO_WINGET = [
    ("wpd", "WPD", "Privacy", "Панель управления приватностью Windows: службы, телеметрия, обновления.",
     "Windows privacy dashboard: services, telemetry, updates."),
    ("dism", "Dism++", "Cleanup", "Графическая оболочка для DISM: чистка компонентов, драйверы, обновления.",
     "A GUI for DISM: component cleanup, drivers, updates."),
    ("wub", "Windows Update Blocker", "Privacy", "Мини-утилита для надёжного отключения автообновлений.",
     "A tiny utility that reliably blocks automatic updates."),
    ("eso", "Easy Service Optimizer", "Optimization", "Отключение лишних служб Windows по готовым пресетам.",
     "Disables unnecessary Windows services using presets."),
    ("nvinspector", "NVIDIA Profile Inspector", "Monitoring", "Скрытые параметры драйвера NVIDIA и профили для отдельных игр.",
     "Hidden NVIDIA driver settings and per-game profiles."),
    ("cleanmgrplus", "Cleanmgr+", "Cleanup", "Современная замена стандартной очистки диска.",
     "A modern replacement for Disk Cleanup."),
    ("ssdlife", "SSD Life", "Storage", "Оценка износа SSD и прогноз оставшегося ресурса.",
     "SSD wear estimation and remaining life forecast."),
    ("oldnewexplorer", "OldNewExplorer", "Interface", "Возвращает классический вид проводника без ленты.",
     "Restores the classic Explorer look without the ribbon."),
]

items = []
for sid, name, cat, winget, pick, ru, en in ITEMS:
    items.append({"id": sid, "name": name, "cat": cat, "winget": winget, "pick": pick, "ru": ru, "en": en, "url": SITE})
for sid, name, cat, ru, en in NO_WINGET:
    items.append({"id": sid, "name": name, "cat": cat, "winget": None, "pick": False, "ru": ru, "en": en, "url": SITE})

db = {"items": items}
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    json.dump(db, f, ensure_ascii=False, separators=(",", ":"))
print("software: %d (winget: %d)" % (len(items), len(ITEMS)))
print("written: %s (%d bytes)" % (os.path.normpath(OUT), os.path.getsize(OUT)))
