from tw_common import *

TELEMETRY_HOSTS = [
    "vortex.data.microsoft.com", "vortex-win.data.microsoft.com", "telecommand.telemetry.microsoft.com",
    "oca.telemetry.microsoft.com", "sqm.telemetry.microsoft.com", "watson.telemetry.microsoft.com",
    "settings-sandbox.data.microsoft.com", "telemetry.microsoft.com", "telemetry.urs.microsoft.com",
    "df.telemetry.microsoft.com", "reports.wes.df.telemetry.microsoft.com",
    "services.wes.df.telemetry.microsoft.com", "sqm.df.telemetry.microsoft.com",
    "watson.ppe.telemetry.microsoft.com", "telemetry.appex.bing.net", "choice.microsoft.com",
    "choice.microsoft.com.nsatc.net", "vortex-sandbox.data.microsoft.com", "survey.watson.microsoft.com",
    "watson.live.com", "watson.microsoft.com", "statsfe2.ws.microsoft.com", "statsfe1.ws.microsoft.com",
    "corp.sts.microsoft.com", "compatexchange.cloudapp.net", "diagnostics.support.microsoft.com",
    "feedback.windows.com", "feedback.microsoft-hohm.com", "feedback.search.microsoft.com",
]

CDM = CVU + r"\ContentDeliveryManager"

ITEMS = [
    T("priv.telemetry-off", "privacy", "safe",
      ("Отключить телеметрию",
       "Политика уровня диагностических данных. Ноль означает, что в Microsoft не уходит ни статистика использования, ни списки установленных программ, ни данные о железе. Обновления безопасности при этом продолжают приходить.",
       None),
      ("Disable telemetry",
       "The diagnostic data level policy. Zero means no usage statistics, no installed app lists and no hardware data go to Microsoft. Security updates keep arriving.",
       None),
      [R("HKLM", POL + r"\DataCollection", "AllowTelemetry", "dword", 0, 1),
       R("HKLM", POL + r"\DataCollection", "MaxTelemetryAllowed", "dword", 0),
       R("HKLM", POL + r"\DataCollection", "DoNotShowFeedbackNotifications", "dword", 1, 0),
       R("HKLM", CV + r"\Policies\DataCollection", "AllowTelemetry", "dword", 0, 1)],
      tags=["privacy"], src="atlas"),

    T("priv.diagtrack-off", "privacy", "safe",
      ("Остановить службу сбора данных",
       "DiagTrack — основной канал отправки телеметрии. Служба работает постоянно и держит открытым соединение с серверами Microsoft. Вместе с ней отключается устаревшая dmwappushservice.",
       None),
      ("Stop the telemetry service",
       "DiagTrack is the main telemetry channel. It runs constantly and keeps a connection to Microsoft open. The legacy dmwappushservice is disabled with it.",
       None),
      [SV("DiagTrack", "disabled", "auto"),
       SV("dmwappushservice", "disabled", "manual"),
       SV("diagnosticshub.standardcollector.service", "disabled", "manual")],
      tags=["privacy"], src="atlas"),

    T("priv.ceip-tasks", "privacy", "safe",
      ("Отключить задачи сбора статистики",
       "Программа улучшения качества и Application Experience запускают по расписанию сборщики данных о запущенных программах и совместимости. Восемь задач в планировщике, которые ничего не дают пользователю.",
       None),
      ("Disable data collection tasks",
       "The Customer Experience Improvement Program and Application Experience run scheduled collectors for app usage and compatibility. Eight tasks that give the user nothing.",
       None),
      [TK(r"\Microsoft\Windows\Customer Experience Improvement Program\Consolidator"),
       TK(r"\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip"),
       TK(r"\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask"),
       TK(r"\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser"),
       TK(r"\Microsoft\Windows\Application Experience\ProgramDataUpdater"),
       TK(r"\Microsoft\Windows\Application Experience\StartupAppTask"),
       TK(r"\Microsoft\Windows\Autochk\Proxy"),
       TK(r"\Microsoft\Windows\Feedback\Siuf\DmClient"),
       TK(r"\Microsoft\Windows\Feedback\Siuf\DmClientOnScenarioDownload"),
       TK(r"\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector")],
      tags=["privacy"], src="atlas"),

    T("priv.appcompat-off", "privacy", "safe",
      ("Отключить инвентаризацию программ",
       "Application Compatibility Telemetry ведёт список всего установленного и запускаемого софта и отправляет его вместе с телеметрией. Это тот самый CompatTelRunner.exe, который иногда грузит диск на сто процентов.",
       None),
      ("Disable app inventory",
       "Application Compatibility Telemetry keeps a list of everything installed and launched and ships it with telemetry. This is the CompatTelRunner.exe that sometimes pins the disk at 100 percent.",
       None),
      [R("HKLM", POL + r"\AppCompat", "AITEnable", "dword", 0, 1),
       R("HKLM", POL + r"\AppCompat", "DisableInventory", "dword", 1, 0),
       R("HKLM", POL + r"\AppCompat", "DisableUAR", "dword", 1, 0),
       R("HKLM", POL + r"\AppCompat", "DisablePCA", "dword", 1, 0)],
      tags=["privacy", "disk"], src="atlas"),

    T("priv.advertising-id", "privacy", "safe",
      ("Отключить рекламный идентификатор",
       "Уникальный номер, по которому приложения из Microsoft Store связывают вашу активность в разных программах для показа рекламы.",
       None),
      ("Disable advertising ID",
       "A unique number that Store apps use to link your activity across programs for ad targeting.",
       None),
      [R("HKCU", CVU + r"\AdvertisingInfo", "Enabled", "dword", 0, 1),
       R("HKLM", POL + r"\AdvertisingInfo", "DisabledByGroupPolicy", "dword", 1, 0)],
      tags=["privacy"]),

    T("priv.activity-history", "privacy", "safe",
      ("Отключить журнал действий",
       "Timeline записывает, какие приложения и документы вы открывали, и синхронизирует это с учётной записью Microsoft.",
       None),
      ("Disable activity history",
       "Timeline records which apps and documents you opened and syncs that with your Microsoft account.",
       None),
      [R("HKLM", POL + r"\System", "EnableActivityFeed", "dword", 0, 1),
       R("HKLM", POL + r"\System", "PublishUserActivities", "dword", 0, 1),
       R("HKLM", POL + r"\System", "UploadUserActivities", "dword", 0, 1)],
      tags=["privacy"]),

    T("priv.suggestions-off", "privacy", "safe",
      ("Убрать рекомендации и рекламу в системе",
       "Плитки «предложенных» приложений в меню Пуск, реклама на экране блокировки, всплывающие советы Windows и тихая установка приложений вроде Candy Crush. Всё это управляется одной веткой ContentDeliveryManager.",
       None),
      ("Remove system ads and suggestions",
       "Suggested app tiles in Start, lock screen ads, Windows tips and the silent install of things like Candy Crush. All driven by the ContentDeliveryManager branch.",
       None),
      [R("HKCU", CDM, "ContentDeliveryAllowed", "dword", 0, 1),
       R("HKCU", CDM, "SilentInstalledAppsEnabled", "dword", 0, 1),
       R("HKCU", CDM, "SystemPaneSuggestionsEnabled", "dword", 0, 1),
       R("HKCU", CDM, "SoftLandingEnabled", "dword", 0, 1),
       R("HKCU", CDM, "PreInstalledAppsEnabled", "dword", 0, 1),
       R("HKCU", CDM, "OemPreInstalledAppsEnabled", "dword", 0, 1),
       R("HKCU", CDM, "RotatingLockScreenOverlayEnabled", "dword", 0, 1),
       R("HKCU", CDM, "SubscribedContent-310093Enabled", "dword", 0, 1),
       R("HKCU", CDM, "SubscribedContent-338387Enabled", "dword", 0, 1),
       R("HKCU", CDM, "SubscribedContent-338388Enabled", "dword", 0, 1),
       R("HKCU", CDM, "SubscribedContent-338389Enabled", "dword", 0, 1),
       R("HKCU", CDM, "SubscribedContent-338393Enabled", "dword", 0, 1),
       R("HKCU", CDM, "SubscribedContent-353694Enabled", "dword", 0, 1),
       R("HKCU", CDM, "SubscribedContent-353696Enabled", "dword", 0, 1),
       R("HKCU", CDM, "SubscribedContent-88000326Enabled", "dword", 0, 1),
       R("HKLM", POL + r"\CloudContent", "DisableWindowsConsumerFeatures", "dword", 1, 0),
       R("HKLM", POL + r"\CloudContent", "DisableCloudOptimizedContent", "dword", 1, 0),
       R("HKCU", POLU + r"\CloudContent", "DisableWindowsSpotlightFeatures", "dword", 1, 0),
       R("HKCU", POLU + r"\CloudContent", "DisableThirdPartySuggestions", "dword", 1, 0)],
      tags=["privacy", "ui"], src="atlas"),

    T("priv.tips-off", "privacy", "safe",
      ("Убрать советы и приветственный экран",
       "Экран «Давайте продолжим настройку устройства» после обновлений и всплывающие подсказки Windows.",
       None),
      ("Remove tips and the welcome screen",
       "The 'Let's finish setting up your device' screen after updates and Windows tip popups.",
       None),
      [R("HKCU", CVU + r"\UserProfileEngagement", "ScoobeSystemSettingEnabled", "dword", 0, 1),
       R("HKCU", CVU + r"\ContentDeliveryManager", "SubscribedContent-310093Enabled", "dword", 0, 1),
       R("HKCU", CVU + r"\Notifications\Settings\Windows.SystemToast.Suggested", "Enabled", "dword", 0, 1)],
      tags=["ui"]),

    T("priv.feedback-off", "privacy", "safe",
      ("Отключить запросы отзывов",
       "Windows периодически спрашивает, насколько вы довольны системой. Здесь частота таких запросов выставляется в ноль.",
       None),
      ("Disable feedback requests",
       "Windows periodically asks how satisfied you are. This sets the frequency of those prompts to zero.",
       None),
      [R("HKCU", r"Software\Microsoft\Siuf\Rules", "NumberOfSIUFInPeriod", "dword", 0, 0),
       R("HKCU", r"Software\Microsoft\Siuf\Rules", "PeriodInNanoSeconds", "dword", 0, 0)],
      tags=["privacy"]),

    T("priv.tailored-off", "privacy", "safe",
      ("Отключить персонализацию по диагностике",
       "Microsoft использует собранную диагностику, чтобы показывать персональные советы и рекламу внутри системы.",
       None),
      ("Disable tailored experiences",
       "Microsoft uses collected diagnostics to show personalised tips and ads inside the system.",
       None),
      [R("HKCU", CVU + r"\Privacy", "TailoredExperiencesWithDiagnosticDataEnabled", "dword", 0, 1),
       R("HKLM", POL + r"\CloudContent", "DisableTailoredExperiencesWithDiagnosticData", "dword", 1, 0)],
      tags=["privacy"]),

    T("priv.typing-off", "privacy", "safe",
      ("Отключить сбор рукописного и печатного ввода",
       "Windows собирает образцы того, как вы печатаете и пишете, чтобы улучшать распознавание. Данные уходят вместе с профилем ввода.",
       None),
      ("Disable typing and inking collection",
       "Windows collects samples of how you type and write to improve recognition. The data leaves with the input profile.",
       None),
      [R("HKCU", r"Software\Microsoft\Input\TIPC", "Enabled", "dword", 0, 1),
       R("HKCU", r"Software\Microsoft\InputPersonalization", "RestrictImplicitInkCollection", "dword", 1, 0),
       R("HKCU", r"Software\Microsoft\InputPersonalization", "RestrictImplicitTextCollection", "dword", 1, 0),
       R("HKCU", r"Software\Microsoft\InputPersonalization\TrainedDataStore", "HarvestContacts", "dword", 0, 1),
       R("HKCU", r"Software\Microsoft\Personalization\Settings", "AcceptedPrivacyPolicy", "dword", 0, 1),
       R("HKLM", POL + r"\InputPersonalization", "AllowInputPersonalization", "dword", 0, 1)],
      tags=["privacy"]),

    T("priv.speech-off", "privacy", "safe",
      ("Отключить онлайн-распознавание речи",
       "Голосовые запросы перестают уходить на серверы Microsoft для распознавания.",
       None),
      ("Disable online speech recognition",
       "Voice input stops being sent to Microsoft servers for recognition.",
       None),
      [R("HKCU", r"Software\Microsoft\Speech_OneCore\Settings\OnlineSpeechPrivacy", "HasAccepted", "dword", 0, 1),
       R("HKLM", POL + r"\InputPersonalization", "AllowInputPersonalization", "dword", 0, 1)],
      tags=["privacy"]),

    T("priv.location-off", "privacy", "advanced",
      ("Отключить геолокацию",
       "Служба определения местоположения и доступ приложений к координатам.",
       "Погода, карты, «Поиск устройства» и автоматический часовой пояс перестанут работать."),
      ("Disable location services",
       "The location service and app access to coordinates.",
       "Weather, Maps, Find My Device and automatic time zone stop working."),
      [R("HKLM", CV + r"\CapabilityAccessManager\ConsentStore\location", "Value", "sz", "Deny", "Allow"),
       R("HKLM", POL + r"\LocationAndSensors", "DisableLocation", "dword", 1, 0),
       SV("lfsvc", "disabled", "manual")],
      tags=["privacy"]),

    T("priv.sync-off", "privacy", "safe",
      ("Отключить синхронизацию настроек",
       "Тема, пароли, язык и настройки браузера перестают уходить в учётную запись Microsoft.",
       None),
      ("Disable settings sync",
       "Theme, passwords, language and browser settings stop syncing to your Microsoft account.",
       None),
      [R("HKLM", POL + r"\SettingSync", "DisableSettingSync", "dword", 2, 1),
       R("HKLM", POL + r"\SettingSync", "DisableSettingSyncUserOverride", "dword", 1, 0)],
      tags=["privacy"]),

    T("priv.cloud-clipboard-off", "privacy", "safe",
      ("Отключить облачный буфер обмена",
       "Синхронизация скопированного текста между устройствами через серверы Microsoft. Локальная история Win+V продолжает работать.",
       None),
      ("Disable cloud clipboard",
       "Syncing copied text between devices through Microsoft servers. The local Win+V history keeps working.",
       None),
      [R("HKLM", POL + r"\System", "AllowCrossDeviceClipboard", "dword", 0, 1)],
      tags=["privacy"]),

    T("priv.background-apps-off", "privacy", "advanced",
      ("Запретить работу приложений в фоне",
       "Приложения из Microsoft Store перестают работать, когда они свёрнуты или закрыты. Освобождает память и убирает фоновый трафик.",
       "Уведомления из магазинных приложений (почта, мессенджеры, календарь) приходить перестанут."),
      ("Block background apps",
       "Store apps stop running when minimised or closed. Frees memory and removes background traffic.",
       "Notifications from Store apps (mail, messengers, calendar) will stop arriving."),
      [R("HKCU", CVU + r"\BackgroundAccessApplications", "GlobalUserDisabled", "dword", 1, 0),
       R("HKLM", POL + r"\AppPrivacy", "LetAppsRunInBackground", "dword", 2, 0),
       R("HKCU", CVU + r"\Search", "BackgroundAppGlobalToggle", "dword", 0, 1)],
      tags=["ram", "privacy"]),

    T("priv.delivery-optimization", "privacy", "safe",
      ("Отключить раздачу обновлений",
       "Delivery Optimization раздаёт скачанные обновления другим компьютерам через интернет, используя ваш канал. На лимитном или медленном подключении это ощутимо.",
       None),
      ("Disable update sharing",
       "Delivery Optimization uploads downloaded updates to other PCs over the internet using your bandwidth. Noticeable on metered or slow links.",
       None),
      [R("HKLM", CV + r"\DeliveryOptimization\Config", "DODownloadMode", "dword", 0, 1),
       R("HKLM", POL + r"\DeliveryOptimization", "DODownloadMode", "dword", 0, 1)],
      tags=["network"]),

    T("priv.edge-telemetry", "privacy", "safe",
      ("Отключить телеметрию Edge",
       "Отправка статистики использования, отзывов и данных о посещённых сайтах из Microsoft Edge. Сам браузер продолжает работать.",
       None),
      ("Disable Edge telemetry",
       "Usage statistics, feedback and browsing data reporting from Microsoft Edge. The browser itself keeps working.",
       None),
      [R("HKLM", r"SOFTWARE\Policies\Microsoft\Edge", "MetricsReportingEnabled", "dword", 0, 1),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\Edge", "SendSiteInfoToImproveServices", "dword", 0, 1),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\Edge", "PersonalizationReportingEnabled", "dword", 0, 1),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\Edge", "UserFeedbackAllowed", "dword", 0, 1),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\Edge", "ShowRecommendationsEnabled", "dword", 0, 1),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\Edge", "StartupBoostEnabled", "dword", 0, 1),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\Edge", "BackgroundModeEnabled", "dword", 0, 1)],
      tags=["privacy", "ram"]),

    T("priv.hosts-telemetry", "privacy", "advanced",
      ("Заблокировать домены телеметрии",
       "Добавляет в файл hosts около тридцати доменов, через которые уходит диагностика. Блок помечен маркерами и снимается той же кнопкой.",
       "Если какой-то сервис Microsoft перестанет работать, снимите блокировку — домены пересекаются с инфраструктурой обновлений."),
      ("Block telemetry domains",
       "Adds about thirty diagnostic domains to the hosts file. The block is marked and removed by the same switch.",
       "If a Microsoft service stops working, unblock it: some domains overlap with update infrastructure."),
      [HS(TELEMETRY_HOSTS)],
      tags=["privacy", "network"]),

    T("ai.copilot-off", "ai", "safe",
      ("Отключить Copilot",
       "Убирает кнопку Copilot с панели задач и запрещает запуск помощника политикой. Без этого он возвращается после обновлений.",
       None),
      ("Disable Copilot",
       "Removes the Copilot button from the taskbar and blocks the assistant by policy. Without the policy it returns after updates.",
       None),
      [R("HKLM", POL + r"\WindowsCopilot", "TurnOffWindowsCopilot", "dword", 1, 0),
       R("HKCU", POLU + r"\WindowsCopilot", "TurnOffWindowsCopilot", "dword", 1, 0),
       R("HKCU", ADV, "ShowCopilotButton", "dword", 0, 1)],
      tags=["privacy", "ui"], req="win11"),

    T("ai.recall-off", "ai", "safe",
      ("Отключить Recall",
       "Recall делает скриншоты экрана каждые несколько секунд и строит по ним поисковый индекс. Политика полностью запрещает анализ данных.",
       None),
      ("Disable Recall",
       "Recall screenshots your screen every few seconds and builds a searchable index. This policy blocks the analysis entirely.",
       None),
      [R("HKLM", POL + r"\WindowsAI", "DisableAIDataAnalysis", "dword", 1, 0),
       R("HKCU", POLU + r"\WindowsAI", "DisableAIDataAnalysis", "dword", 1, 0),
       R("HKLM", POL + r"\WindowsAI", "AllowRecallEnablement", "dword", 0, 1)],
      tags=["privacy"], req="win11"),

    T("ai.cortana-off", "ai", "safe",
      ("Отключить Cortana",
       "Голосовой помощник и его фоновые процессы. На современных сборках Cortana почти не используется, но всё ещё запускается.",
       None),
      ("Disable Cortana",
       "The voice assistant and its background processes. Barely used on current builds but still launched.",
       None),
      [R("HKLM", POL + r"\Windows Search", "AllowCortana", "dword", 0, 1),
       R("HKLM", POL + r"\Windows Search", "DisableWebSearch", "dword", 1, 0),
       R("HKLM", POL + r"\Windows Search", "ConnectedSearchUseWeb", "dword", 0, 1)],
      tags=["privacy", "ram"]),

    T("ai.bing-search-off", "ai", "safe",
      ("Убрать интернет-поиск из меню Пуск",
       "Каждый запрос в меню Пуск сейчас уходит в Bing и возвращается веб-результатами поверх локальных файлов. Это и утечка запросов, и задержка при поиске.",
       None),
      ("Remove web search from Start",
       "Every Start menu query currently goes to Bing and returns web results above your local files. That is both a query leak and a delay.",
       None),
      [R("HKCU", CVU + r"\Search", "BingSearchEnabled", "dword", 0, 1),
       R("HKCU", CVU + r"\Search", "CortanaConsent", "dword", 0, 1),
       R("HKCU", POLU + r"\Explorer", "DisableSearchBoxSuggestions", "dword", 1, 0),
       R("HKLM", POL + r"\Explorer", "DisableSearchBoxSuggestions", "dword", 1, 0)],
      tags=["privacy", "ui"]),

    T("upd.no-auto-restart", "updates", "safe",
      ("Запретить перезагрузку без спроса",
       "Windows не будет перезагружать компьютер для завершения обновления, пока в системе есть вошедший пользователь.",
       None),
      ("Block automatic restart",
       "Windows will not reboot to finish an update while a user is signed in.",
       None),
      [R("HKLM", POL + r"\WindowsUpdate\AU", "NoAutoRebootWithLoggedOnUsers", "dword", 1, 0),
       R("HKLM", POL + r"\WindowsUpdate\AU", "AUPowerManagement", "dword", 0, 1)],
      tags=["updates"]),

    T("upd.no-driver-updates", "updates", "advanced",
      ("Не обновлять драйверы через Windows Update",
       "Windows Update регулярно подменяет драйвер видеокарты или звука на свою версию, часто более старую. Обновления системы при этом продолжают приходить.",
       "Драйверы придётся ставить вручную с сайта производителя."),
      ("No driver updates from Windows Update",
       "Windows Update regularly replaces your GPU or audio driver with its own, often older, version. System updates keep arriving.",
       "You will install drivers manually from the vendor site."),
      [R("HKLM", POL + r"\WindowsUpdate", "ExcludeWUDriversInQualityUpdate", "dword", 1, 0),
       R("HKLM", CV + r"\DriverSearching", "SearchOrderConfig", "dword", 0, 1),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\Windows NT\Driver Searching", "DontSearchWindowsUpdate", "dword", 1, 0)],
      tags=["updates", "stability"]),

    T("upd.manual", "updates", "advanced",
      ("Обновления только вручную",
       "Windows перестаёт скачивать и ставить обновления сама — они появляются в Центре обновления и ждут нажатия кнопки.",
       "Обновления безопасности не будут устанавливаться, пока вы не запустите их сами."),
      ("Manual updates only",
       "Windows stops downloading and installing updates on its own; they wait in Windows Update for you to click.",
       "Security updates will not install until you start them yourself."),
      [R("HKLM", POL + r"\WindowsUpdate\AU", "NoAutoUpdate", "dword", 1, 0),
       R("HKLM", POL + r"\WindowsUpdate\AU", "AUOptions", "dword", 2, 4)],
      tags=["updates"]),

    T("upd.store-auto-off", "updates", "advanced",
      ("Отключить автообновление приложений Store",
       "Магазин перестаёт обновлять приложения в фоне. Обновить вручную можно в любой момент.",
       None),
      ("Disable Store auto-updates",
       "The Store stops updating apps in the background. Manual updates remain available.",
       None),
      [R("HKLM", r"SOFTWARE\Policies\Microsoft\WindowsStore", "AutoDownload", "dword", 2, 4)],
      tags=["updates", "network"]),

    T("upd.full-off", "updates", "extreme",
      ("Полностью отключить Windows Update",
       "Останавливает службу обновлений, службу доставки, оркестратор и службу восстановления Update Medic, которая обычно включает всё обратно.",
       "Ваша система перестанет получать исправления безопасности. Через несколько месяцев это реальный риск заражения. Включайте обратно перед каждым обслуживанием."),
      ("Fully disable Windows Update",
       "Stops the update service, delivery service, orchestrator and the Update Medic service that normally turns everything back on.",
       "Your system stops receiving security fixes. After a few months that is a real infection risk. Re-enable before any maintenance."),
      [SV("wuauserv", "disabled", "manual"),
       SV("UsoSvc", "disabled", "manual"),
       SV("WaaSMedicSvc", "disabled", "manual"),
       SV("DoSvc", "disabled", "manual"),
       R("HKLM", POL + r"\WindowsUpdate\AU", "NoAutoUpdate", "dword", 1, 0)],
      tags=["updates"]),

    T("sec.smartscreen-off", "security", "extreme",
      ("Отключить SmartScreen",
       "SmartScreen проверяет запускаемые файлы и посещаемые сайты через репутационную базу Microsoft. Отключение убирает задержку при первом запуске скачанных программ и отправку хешей файлов.",
       "Пропадёт предупреждение при запуске вредоносных файлов из интернета."),
      ("Disable SmartScreen",
       "SmartScreen checks launched files and visited sites against Microsoft's reputation database. Disabling removes the first-run delay and the file hash upload.",
       "You lose the warning when running malicious files from the internet."),
      [R("HKLM", POL + r"\System", "EnableSmartScreen", "dword", 0, 1),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\Edge", "SmartScreenEnabled", "dword", 0, 1),
       R("HKCU", CVU + r"\AppHost", "EnableWebContentEvaluation", "dword", 0, 1)],
      tags=["privacy"]),

    T("sec.defender-off", "security", "extreme",
      ("Отключить Защитник Windows",
       "Политики полного отключения антивируса и защиты в реальном времени. Даёт заметный прирост при компиляции, распаковке и первом запуске игр.",
       "Работает только при выключенной защите от подделки (Tamper Protection): Безопасность Windows — Защита от вирусов — Параметры — Защита от подделки. Без антивируса компьютер остаётся беззащитным перед любым скачанным файлом."),
      ("Disable Windows Defender",
       "Policies that fully disable the antivirus and real-time protection. Gives a clear speedup in compiling, extracting and first game launches.",
       "Only works with Tamper Protection off: Windows Security - Virus protection - Settings - Tamper Protection. Without an antivirus the machine is defenceless against any downloaded file."),
      [R("HKLM", r"SOFTWARE\Policies\Microsoft\Windows Defender", "DisableAntiSpyware", "dword", 1, 0),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\Windows Defender", "DisableAntiVirus", "dword", 1, 0),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection", "DisableRealtimeMonitoring", "dword", 1, 0),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection", "DisableBehaviorMonitoring", "dword", 1, 0),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection", "DisableScanOnRealtimeEnable", "dword", 1, 0),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\Windows Defender\Spynet", "SpynetReporting", "dword", 0, 2),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\Windows Defender\Spynet", "SubmitSamplesConsent", "dword", 2, 1)],
      tags=["fps", "cpu"], restart=True),

    T("sec.vbs-off", "security", "extreme",
      ("Отключить виртуализацию безопасности (VBS)",
       "Изоляция ядра и целостность памяти работают через гипервизор и стабильно отнимают от 5 до 15 процентов производительности в играх. На игровом ПК это самый крупный единичный прирост FPS из всех твиков.",
       "Снижается защита от эксплойтов уровня ядра. Некоторые античиты (Vanguard, Faceit) требуют включённой изоляции ядра и перестанут пускать в игру."),
      ("Disable Virtualization-Based Security",
       "Core isolation and memory integrity run through the hypervisor and consistently cost 5 to 15 percent of gaming performance. On a gaming PC this is the single biggest FPS win here.",
       "Kernel-level exploit protection drops. Some anti-cheats (Vanguard, Faceit) require core isolation and will refuse to launch."),
      [R("HKLM", CCS + r"\Control\DeviceGuard", "EnableVirtualizationBasedSecurity", "dword", 0, 1),
       R("HKLM", CCS + r"\Control\DeviceGuard\Scenarios\HypervisorEnforcedCodeIntegrity", "Enabled", "dword", 0, 1),
       R("HKLM", CCS + r"\Control\DeviceGuard", "HypervisorEnforcedCodeIntegrity", "dword", 0, 1),
       CM("bcdedit.exe", "/set hypervisorlaunchtype off", "/set hypervisorlaunchtype auto")],
      tags=["fps", "gpu"], src="atlas", restart=True),

    T("sec.uac-lower", "security", "extreme",
      ("Убрать запрос UAC для администратора",
       "Программы, запускаемые администратором, перестают спрашивать подтверждение. Сам UAC остаётся включённым, поэтому магазинные приложения и изоляция продолжают работать.",
       "Любая запущенная вами программа получит полные права без единого вопроса. Одного случайного запуска вредоносного файла будет достаточно."),
      ("Silent UAC elevation for admins",
       "Programs launched by an administrator stop asking for confirmation. UAC itself stays on, so Store apps and isolation keep working.",
       "Any program you run gets full rights with no prompt. One accidental launch of a malicious file is enough."),
      [R("HKLM", CV + r"\Policies\System", "ConsentPromptBehaviorAdmin", "dword", 0, 5),
       R("HKLM", CV + r"\Policies\System", "PromptOnSecureDesktop", "dword", 0, 1)],
      tags=["ui"]),

    T("net.llmnr-off", "network", "safe",
      ("Отключить LLMNR",
       "Устаревший протокол разрешения имён в локальной сети. Сейчас используется в основном для перехвата учётных данных в корпоративных сетях, а на домашнем ПК не нужен.",
       None),
      ("Disable LLMNR",
       "A legacy local name resolution protocol. Nowadays mostly used for credential interception on corporate networks and unnecessary at home.",
       None),
      [R("HKLM", r"SOFTWARE\Policies\Microsoft\Windows NT\DNSClient", "EnableMulticast", "dword", 0, 1)],
      tags=["network", "privacy"]),

    T("net.qos-off", "network", "advanced",
      ("Снять резерв канала под QoS",
       "Windows по умолчанию резервирует до 20 процентов пропускной способности под приоритетный трафик. На домашнем канале эта квота почти никогда не используется по назначению.",
       None),
      ("Remove QoS bandwidth reserve",
       "Windows reserves up to 20 percent of bandwidth for prioritised traffic. On a home link that quota is almost never used as intended.",
       None),
      [R("HKLM", POL + r"\Psched", "NonBestEffortLimit", "dword", 0, 20)],
      tags=["network"]),

    T("net.dns-cache", "network", "safe",
      ("Увеличить кэш DNS",
       "Ответы DNS хранятся сутки вместо нескольких минут, а неудачные запросы не кэшируются вовсе. Меньше повторных обращений к серверу при открытии сайтов.",
       None),
      ("Tune the DNS cache",
       "DNS answers are kept for a day instead of minutes and failures are not cached at all. Fewer repeat lookups when opening sites.",
       None),
      [R("HKLM", CCS + r"\Services\Dnscache\Parameters", "MaxCacheTtl", "dword", 86400, 86400),
       R("HKLM", CCS + r"\Services\Dnscache\Parameters", "MaxNegativeCacheTtl", "dword", 0, 5)],
      tags=["network"]),

    T("net.tcp-tuning", "network", "advanced",
      ("Настроить стек TCP под низкий пинг",
       "Отключает ECN и коалесцирование сегментов, включает масштабирование окна и RSS. Для онлайн-игр это убирает часть задержки, которую добавляет сама Windows.",
       "На нестабильном или спутниковом канале ECN иногда помогает — если пинг ухудшился, откатите."),
      ("Tune the TCP stack for low ping",
       "Turns ECN and receive segment coalescing off, enables window scaling and RSS. For online games this removes latency that Windows itself adds.",
       "On unstable or satellite links ECN sometimes helps: revert if your ping got worse."),
      [CM("netsh.exe", "int tcp set global ecncapability=disabled rsc=disabled rss=enabled autotuninglevel=normal",
          "int tcp set global ecncapability=default rsc=default rss=enabled autotuninglevel=normal")],
      tags=["network", "latency"]),

    T("net.ipv6-off", "network", "advanced",
      ("Отключить IPv6",
       "Если провайдер не выдаёт IPv6, система всё равно пытается использовать его первым при каждом обращении и ждёт таймаута. Отключение убирает эту паузу.",
       "Если у вас есть IPv6 или вы используете сервисы, работающие только по нему, связь сломается. Часть VPN тоже требует IPv6."),
      ("Disable IPv6",
       "If your ISP gives no IPv6, the system still tries it first on every lookup and waits for a timeout. Disabling removes that pause.",
       "If you do have IPv6 or use IPv6-only services, connectivity breaks. Some VPNs need it too."),
      [R("HKLM", CCS + r"\Services\Tcpip6\Parameters", "DisabledComponents", "dword", "0xFF", 0)],
      tags=["network"], restart=True),

    T("net.wifi-sense-off", "network", "safe",
      ("Отключить Wi-Fi Sense",
       "Автоматическое подключение к открытым точкам и обмен паролями сетей с контактами.",
       None),
      ("Disable Wi-Fi Sense",
       "Automatic connection to open hotspots and sharing network passwords with contacts.",
       None),
      [R("HKLM", r"SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\config", "AutoConnectAllowedOEM", "dword", 0, 1),
       R("HKLM", r"SOFTWARE\Microsoft\PolicyManager\default\WiFi\AllowAutoConnectToWiFiSenseHotspots", "value", "dword", 0, 1)],
      tags=["network", "privacy"]),
]
