from tw_common import *

ENV = CCS + r"\Control\Session Manager\Environment"
CDM = CVU + r"\ContentDeliveryManager"
EDGEPOL = r"SOFTWARE\Policies\Microsoft\Edge"
WSC = r"SOFTWARE\Policies\Microsoft\Windows Defender Security Center\Notifications"
PV = r"SOFTWARE\Classes\Applications\photoviewer.dll\shell\open"
PVCMD = r"%SystemRoot%\System32\rundll32.exe \"%ProgramFiles%\Windows Photo Viewer\PhotoViewer.dll\", ImageView_Fullscreen %1"

ITEMS = [
    T("priv.dotnet-telemetry", "privacy", "safe",
      ("Телеметрия .NET и dotnet CLI",
       "Каждая команда dotnet отправляет в Microsoft сведения о том, что вы собирали: версию SDK, тип проекта, операционную систему, хешированный путь. Переменная окружения отключает это для всех версий SDK сразу и навсегда, а не для одного запуска.",
       None),
      (".NET and dotnet CLI telemetry",
       "Every dotnet command reports to Microsoft what you built: the SDK version, the project type, the operating system, a hashed path. One environment variable turns that off for every SDK version at once and permanently, not for a single run.",
       None),
      [R("HKLM", ENV, "DOTNET_CLI_TELEMETRY_OPTOUT", "sz", "1")],
      tags=["telemetry", "dev"], logoff=True),

    T("priv.powershell-telemetry", "privacy", "safe",
      ("Телеметрия PowerShell",
       "PowerShell 7 при каждом запуске сообщает Microsoft версию, платформу и способ установки. Классический Windows PowerShell 5.1 этого не делает, так что твик касается только установленной отдельно семёрки.",
       None),
      ("PowerShell telemetry",
       "PowerShell 7 reports its version, platform and install method to Microsoft on every start. The classic Windows PowerShell 5.1 does not, so this only affects a separately installed 7.",
       None),
      [R("HKLM", ENV, "POWERSHELL_TELEMETRY_OPTOUT", "sz", "1")],
      tags=["telemetry", "dev"], logoff=True),

    T("priv.devtools-telemetry", "privacy", "safe",
      ("Телеметрия инструментов разработчика",
       "Одним махом выставляет переменные отказа, которые понимают десятки инструментов: Azure CLI, Next.js, Gatsby, AWS SAM и всё, что уважает общепринятую переменную DO_NOT_TRACK. Работает и для тех, что появятся позже, — переменная стандартная.",
       None),
      ("Developer tooling telemetry",
       "Sets the opt-out variables understood by dozens of tools at once: Azure CLI, Next.js, Gatsby, AWS SAM and anything that respects the common DO_NOT_TRACK variable. It also covers tools installed later, since the variable is a convention.",
       None),
      [R("HKLM", ENV, "DO_NOT_TRACK", "sz", "1"),
       R("HKLM", ENV, "AZURE_CORE_COLLECT_TELEMETRY", "sz", "0"),
       R("HKLM", ENV, "NEXT_TELEMETRY_DISABLED", "sz", "1"),
       R("HKLM", ENV, "GATSBY_TELEMETRY_DISABLED", "sz", "1"),
       R("HKLM", ENV, "SAM_CLI_TELEMETRY", "sz", "0")],
      tags=["telemetry", "dev"], logoff=True),

    T("priv.vs-telemetry", "privacy", "safe",
      ("Телеметрия Visual Studio",
       "Visual Studio собирает статистику использования и отчёты о зависаниях и отправляет их в программу улучшения качества. Политика выключает и саму телеметрию, и участие в программе.",
       None),
      ("Visual Studio telemetry",
       "Visual Studio collects usage statistics and hang reports and sends them to the experience improvement program. The policy turns off both the telemetry and the enrolment.",
       None),
      [R("HKCU", r"Software\Microsoft\VisualStudio\Telemetry", "TurnOffSwitch", "dword", 1, 0),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\VisualStudio\SQM", "OptIn", "dword", 0, 1),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\VisualStudio\Feedback", "DisableFeedbackDialog", "dword", 1, 0),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\VisualStudio\Feedback", "DisableEmailInput", "dword", 1, 0),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\VisualStudio\Feedback", "DisableScreenshotCapture", "dword", 1, 0)],
      tags=["telemetry", "dev"]),

    T("priv.license-telemetry", "privacy", "safe",
      ("Телеметрия лицензирования",
       "Платформа защиты программного обеспечения периодически выпускает и отправляет тикет со сведениями о лицензии и оборудовании. Это отдельный канал, который не закрывается общим отключением телеметрии.",
       None),
      ("Licensing telemetry",
       "The software protection platform periodically issues and sends a ticket with licence and hardware details. It is a separate channel that the general telemetry switch does not cover.",
       None),
      [R("HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Software Protection Platform", "NoGenTicket", "dword", 1, 0)],
      tags=["telemetry"]),

    T("priv.ucpd-off", "privacy", "advanced",
      ("Отключить UCPD (защиту выбора по умолчанию)",
       "User Choice Protection Driver появился в Windows 11 и следит за тем, какой браузер и почтовый клиент назначены по умолчанию. Если сменить их не через «Параметры», а любым другим способом, драйвер молча откатывает изменение обратно, и понять причину со стороны невозможно.",
       "Программы снова смогут назначать себя браузером и почтовым клиентом по умолчанию без вашего участия."),
      ("Disable UCPD (default-choice protection)",
       "The User Choice Protection Driver arrived in Windows 11 and guards which browser and mail client are set as default. Change them by any route other than Settings and the driver silently reverts it, with nothing to explain why.",
       "Programs will again be able to make themselves the default browser and mail client without asking."),
      [SV("UCPD", "disabled", "manual", stop=False),
       TK(r"\Microsoft\Windows\AppxDeploymentClient\UCPD velocity")],
      tags=["control"], restart=True),

    T("perf.hpet-off", "performance", "advanced",
      ("Снять принудительный HPET",
       "Высокоточный таймер событий — медленный аппаратный источник времени. Windows сама выбирает счётчик получше, но параметр загрузчика useplatformclock может принудительно посадить систему на HPET. Его любят выставлять другие твикеры и утилиты разгона, после чего растёт задержка ввода и падает частота кадров. Твик убирает этот параметр и возвращает выбор системе.",
       "Не будет работать: принудительный выбор HPET, если его выставила другая программа. Откат убирает наш параметр целиком и возвращает выбор таймера системе."),
      ("Remove the forced HPET",
       "The High Precision Event Timer is a slow hardware time source. Windows picks a better counter on its own, but the useplatformclock boot parameter can pin the system to HPET. Other tweakers and overclocking utilities like to set it, after which input latency rises and frame rates drop. This removes the parameter and hands the choice back to the system.",
       "Will stop working: any forced HPET selection another program set. Reverting removes our parameter entirely and hands the timer choice back to the system."),
      [CM("bcdedit.exe", "/set useplatformclock false", "/deletevalue useplatformclock")],
      tags=["latency", "fps"], src="atlas", restart=True),

    T("sec.autoencrypt-off", "security", "advanced",
      ("Запретить автоматическое шифрование диска",
       "Windows 11 на подходящем оборудовании шифрует системный диск сама, при первом входе в учётную запись Microsoft. Ключ уезжает в облако, а пользователь чаще всего об этом не знает — пока не переставит материнскую плату и не обнаружит, что диск не читается.",
       "Диск останется незашифрованным. Если ноутбук потеряют, данные с него прочитают без пароля."),
      ("Block automatic drive encryption",
       "On capable hardware Windows 11 encrypts the system drive by itself at the first sign-in with a Microsoft account. The key goes to the cloud and most people never learn it happened — until they swap the motherboard and find the drive unreadable.",
       "The drive stays unencrypted. If the laptop is lost, its data can be read without a password."),
      [R("HKLM", CCS + r"\Control\BitLocker", "PreventDeviceEncryption", "dword", 1, 0)],
      tags=["disk"], req="win11"),

    T("sec.defender-notify-off", "security", "safe",
      ("Убрать уведомления Защитника",
       "Всплывающие сводки «угроз не найдено», напоминания включить что-нибудь и предложения купить подписку. Сама защита продолжает работать в полном объёме — выключаются только уведомления.",
       "Не будет работать: всплывающие уведомления о найденных угрозах. Иконка в трее и окно «Безопасность Windows» продолжат показывать состояние."),
      ("Silence Defender notifications",
       "The popup summaries saying no threats were found, the reminders to turn something on and the subscription offers. Protection itself keeps working in full — only the notifications go.",
       "Will stop working: popup notifications about detected threats. The tray icon and the Windows Security window still show the state."),
      [R("HKLM", WSC, "DisableNotifications", "dword", 1, 0),
       R("HKLM", WSC, "DisableEnhancedNotifications", "dword", 1, 0)],
      tags=["ui"]),

    T("sec.firewall-off", "security", "extreme",
      ("Отключить брандмауэр Windows",
       "Полностью снимает фильтрацию входящих и исходящих соединений во всех трёх профилях: доменном, частном и публичном. Машина становится видимой и доступной из локальной сети без каких-либо ограничений.",
       "Не будет работать: XBOX и игры, которым нужен брандмауэр для сопоставления. Любая программа сможет принимать соединения извне. В публичной сети — кафе, общежитие, отель — это прямой путь к заражению."),
      ("Disable the Windows firewall",
       "Removes inbound and outbound filtering entirely across all three profiles: domain, private and public. The machine becomes visible and reachable on the local network with no restrictions.",
       "Will stop working: XBOX and games that need the firewall for matchmaking. Any program can accept inbound connections. On a public network — a cafe, a dorm, a hotel — this is a direct route to infection."),
      [R("HKLM", CCS + r"\Services\SharedAccess\Parameters\FirewallPolicy\DomainProfile", "EnableFirewall", "dword", 0, 1),
       R("HKLM", CCS + r"\Services\SharedAccess\Parameters\FirewallPolicy\StandardProfile", "EnableFirewall", "dword", 0, 1),
       R("HKLM", CCS + r"\Services\SharedAccess\Parameters\FirewallPolicy\PublicProfile", "EnableFirewall", "dword", 0, 1),
       SV("mpssvc", "disabled", "auto", stop=False)],
      tags=["network"], restart=True),

    T("ui.wallpaper-quality", "interface", "safe",
      ("Не пережимать обои рабочего стола",
       "Windows пересохраняет любую картинку для рабочего стола в JPEG с качеством около 85 процентов, из-за чего на градиентах и тёмных участках появляются квадраты и полосы. Значение 100 отключает пережатие, и обои выглядят так, как выглядел исходный файл.",
       None),
      ("Stop recompressing the wallpaper",
       "Windows re-saves any desktop picture as JPEG at about 85 percent quality, which puts blocks and banding into gradients and dark areas. Setting 100 turns the recompression off and the wallpaper looks like the original file.",
       None),
      [R("HKCU", r"Control Panel\Desktop", "JPEGImportQuality", "dword", 100, None)],
      tags=["ui"], logoff=True),

    T("ui.photo-viewer", "interface", "safe",
      ("Вернуть старый просмотрщик фотографий",
       "Средство просмотра фотографий Windows никуда не делось из системы, у него лишь убрали регистрацию. Твик возвращает его в список «Открыть с помощью»: оно открывается мгновенно, не запрашивает обновлений и не показывает рекламу, в отличие от приложения «Фотографии».",
       None),
      ("Bring back the old photo viewer",
       "Windows Photo Viewer never left the system, it just lost its registration. This puts it back into the Open With list: it opens instantly and never asks for updates or shows ads, unlike the Photos app.",
       None),
      [R("HKLM", PV, "MuiVerb", "sz", "@photoviewer.dll,-3043"),
       R("HKLM", PV + r"\command", "", "expand", PVCMD),
       R("HKLM", PV + r"\DropTarget", "Clsid", "sz", "{FFE2A43C-56B9-4bf5-9A79-CC6D4285608A}"),
       R("HKLM", r"SOFTWARE\Classes\.jpg\OpenWithList\photoviewer.dll", "", "sz", ""),
       R("HKLM", r"SOFTWARE\Classes\.jpeg\OpenWithList\photoviewer.dll", "", "sz", ""),
       R("HKLM", r"SOFTWARE\Classes\.png\OpenWithList\photoviewer.dll", "", "sz", ""),
       R("HKLM", r"SOFTWARE\Classes\.bmp\OpenWithList\photoviewer.dll", "", "sz", ""),
       R("HKLM", r"SOFTWARE\Classes\.gif\OpenWithList\photoviewer.dll", "", "sz", ""),
       R("HKLM", r"SOFTWARE\Classes\.tif\OpenWithList\photoviewer.dll", "", "sz", "")],
      tags=["ui"]),

    T("ui.dynamic-lighting-off", "interface", "safe",
      ("Отключить динамическое освещение",
       "Windows 11 перехватывает управление подсветкой у родного софта материнской платы, мыши и клавиатуры и красит всё в свой акцентный цвет. Профили в iCUE, Armoury Crate или G HUB при этом перестают применяться, а фоновая служба остаётся в памяти.",
       None),
      ("Disable Dynamic Lighting",
       "Windows 11 takes RGB control away from the software that came with the motherboard, mouse and keyboard and paints everything in its accent colour. Profiles in iCUE, Armoury Crate or G HUB stop applying, and the background service stays in memory.",
       None),
      [R("HKCU", CVU + r"\Lighting", "AmbientLightingEnabled", "dword", 0, 1),
       R("HKCU", CVU + r"\Lighting", "ControlledByForegroundApp", "dword", 0, 1),
       R("HKCU", CVU + r"\Lighting", "UseSystemAccentColor", "dword", 0, 1)],
      tags=["ui"], req="win11"),

    T("ui.lockscreen-off", "interface", "safe",
      ("Пропускать экран блокировки",
       "Картинка, которую нужно смахнуть или щёлкнуть, прежде чем появится поле ввода пароля. Экран входа при этом остаётся: убирается только лишний шаг перед ним.",
       "Не будет работать: картинки и подсказки Windows Spotlight на экране блокировки."),
      ("Skip the lock screen",
       "The picture you have to swipe or click away before the password box appears. The sign-in screen stays — only the extra step before it goes.",
       "Will stop working: Windows Spotlight pictures and tips on the lock screen."),
      [R("HKLM", POL + r"\Personalization", "NoLockScreen", "dword", 1, 0)],
      tags=["ui"]),

    T("ui.spotlight-off", "interface", "safe",
      ("Отключить Windows Spotlight",
       "Меняющиеся картинки на экране блокировки подгружаются из интернета вместе с рекламными подсказками, ссылками на приложения магазина и предложениями попробовать подписку. Фоновая загрузка идёт постоянно, даже на лимитном подключении.",
       None),
      ("Disable Windows Spotlight",
       "The rotating lock screen pictures are fetched from the internet together with promotional tips, links to Store apps and subscription offers. The background download runs constantly, even on a metered connection.",
       None),
      [R("HKCU", CDM, "RotatingLockScreenEnabled", "dword", 0, 1),
       R("HKCU", CDM, "RotatingLockScreenOverlayEnabled", "dword", 0, 1),
       R("HKCU", CDM, "SubscribedContent-338387Enabled", "dword", 0, 1),
       R("HKCU", CDM, "SubscribedContent-338388Enabled", "dword", 0, 1),
       R("HKCU", CDM, "SubscribedContent-338389Enabled", "dword", 0, 1)],
      tags=["ui", "telemetry"]),

    T("ui.alt-tab-classic", "interface", "safe",
      ("Старое переключение окон по Alt+Tab",
       "Вместо панели с крупными живыми миниатюрами возвращается маленькое окно со значками, как было до Windows Vista. Переключение перестаёт зависеть от диспетчера окон и происходит мгновенно даже на слабой видеокарте.",
       "Не будет работать: предпросмотр содержимого окон при переключении и вкладки браузера в Alt+Tab."),
      ("Classic Alt+Tab window switcher",
       "Instead of a panel of large live thumbnails you get the small icon box from before Windows Vista. Switching no longer goes through the window manager and is instant even on a weak GPU.",
       "Will stop working: window content previews while switching and browser tabs in Alt+Tab."),
      [R("HKCU", ADV, "AltTabSettings", "dword", 1, 0)],
      tags=["ui", "gpu"], logoff=True),

    T("ui.tray-all-icons", "interface", "safe",
      ("Показывать все значки в трее",
       "Windows прячет значки запущенных программ в выпадающую стрелку, и понять, что именно висит в фоне, можно только раскрыв её. Здесь все значки показываются сразу.",
       None),
      ("Show every tray icon",
       "Windows hides the icons of running programs behind a chevron, so the only way to see what is in the background is to expand it. This shows them all at once.",
       None),
      [R("HKCU", CVU + r"\Explorer", "EnableAutoTray", "dword", 0, 1)],
      tags=["ui"], logoff=True),

    T("ui.mobility-center-off", "interface", "safe",
      ("Отключить Центр мобильности",
       "Окно с яркостью, громкостью и батареей, которое открывается по Win+X и сочетанию клавиш на ноутбуках. Всё то же самое давно есть в панели быстрых настроек, а окно осталось с Windows Vista.",
       None),
      ("Disable the Mobility Center",
       "The window with brightness, volume and battery that opens from Win+X and a key combination on laptops. Everything in it has long been in the quick settings panel, while the window itself is a leftover from Windows Vista.",
       None),
      [R("HKCU", CVU + r"\Policies\MobilityCenter", "NoMobilityCenter", "dword", 1, 0)],
      tags=["ui"], req="laptop"),

    T("ui.news-interests-off", "interface", "safe",
      ("Отключить «Новости и интересы»",
       "Лента новостей и погоды на панели задач подгружает содержимое и рекламу в фоне и держит для этого отдельный процесс. Отключается политикой, поэтому не возвращается после обновления, в отличие от переключателя в интерфейсе.",
       None),
      ("Disable News and Interests",
       "The news and weather feed on the taskbar pulls content and ads in the background and keeps its own process for it. This turns it off by policy, so it does not come back after an update, unlike the switch in the interface.",
       None),
      [R("HKLM", POL + r"\Windows Feeds", "EnableFeeds", "dword", 0, 1)],
      tags=["ui", "telemetry"]),

    T("ui.notifications-off", "interface", "safe",
      ("Отключить всплывающие уведомления",
       "Полностью убирает всплывающие карточки в правом нижнем углу и звук к ним. Центр уведомлений остаётся доступным, уведомления в нём копятся — просто перестают отвлекать поверх игры или работы.",
       "Не будет работать: всплывающие напоминания календаря, уведомления мессенджеров и предупреждения системы. Их придётся смотреть в центре уведомлений."),
      ("Disable toast notifications",
       "Removes the popup cards in the bottom right corner and their sound entirely. The notification centre stays available and still collects them — they simply stop interrupting a game or your work.",
       "Will stop working: popup calendar reminders, messenger notifications and system warnings. You will have to look for them in the notification centre."),
      [R("HKCU", CVU + r"\PushNotifications", "ToastEnabled", "dword", 0, 1),
       R("HKCU", CVU + r"\Notifications\Settings", "NOC_GLOBAL_SETTING_ALLOW_TOASTS_ABOVE_LOCK", "dword", 0, 1)],
      tags=["ui"], logoff=True),

    T("app.teams-autoinstall-off", "debloat", "safe",
      ("Запретить автоустановку Teams",
       "Windows 11 ставит Teams заново при создании нового профиля и после части обновлений, даже если его только что удалили. Политика убирает автоустановку и заодно значок чата с панели задач.",
       None),
      ("Block the Teams auto-install",
       "Windows 11 reinstalls Teams when a new profile is created and after some updates, even right after it was removed. The policy stops the auto-install and takes the chat icon off the taskbar with it.",
       None),
      [R("HKLM", CV + r"\Communications", "ConfigureChatAutoInstall", "dword", 0, 1),
       R("HKLM", POL + r"\Windows Chat", "ChatIcon", "dword", 3, 1)],
      tags=["debloat"], req="win11"),

    T("upd.maps-off", "updates", "safe",
      ("Отключить автообновление карт",
       "Офлайн-карты обновляются в фоне по расписанию и скачивают сотни мегабайт, даже если приложением «Карты» никогда не пользовались. Отключается и сама загрузка, и задача планировщика, которая её запускает.",
       None),
      ("Disable automatic map updates",
       "Offline maps update in the background on a schedule and pull down hundreds of megabytes, even if the Maps app was never opened. This turns off both the download and the scheduled task that starts it.",
       None),
      [R("HKLM", r"SYSTEM\Maps", "AutoUpdateEnabled", "dword", 0, 1),
       TK(r"\Microsoft\Windows\Maps\MapsUpdateTask"),
       TK(r"\Microsoft\Windows\Maps\MapsToastTask")],
      tags=["network", "disk"]),

    T("priv.edge-background-off", "privacy", "safe",
      ("Edge не работает в фоне",
       "Edge держит процессы в памяти после закрытия окна и запускает себя при входе в систему, чтобы открываться быстрее. На слабой машине это занятая память и лишний старт, а на любой — фоновое соединение с серверами Microsoft.",
       "Edge будет открываться немного дольше после входа в систему."),
      ("Stop Edge running in the background",
       "Edge keeps processes in memory after the window is closed and starts itself at sign-in so it opens faster. On a weak machine that is occupied memory and an extra startup item, and on any machine a background connection to Microsoft servers.",
       "Edge will take slightly longer to open after signing in."),
      [R("HKLM", EDGEPOL, "StartupBoostEnabled", "dword", 0, 1),
       R("HKLM", EDGEPOL, "BackgroundModeEnabled", "dword", 0, 1)],
      tags=["ram", "telemetry"]),
]
