from tw_common import *

MOUSE = CCS + r"\Services\mouclass\Parameters"
KBD = CCS + r"\Services\kbdclass\Parameters"
OFF16 = r"Software\Microsoft\Office\16.0\Common"
OFFPOL = r"Software\Policies\Microsoft\office\16.0\common"

ITEMS = [
    T("input.mouse-queue", "input", "advanced",
      ("Уменьшить буфер мыши",
       "Драйвер мыши складывает пакеты в очередь на 100 позиций, прежде чем отдать их системе. Значение 20 укорачивает очередь: движения доходят до игры раньше, буферизации меньше. Один из ключевых твиков Atlas для соревновательных шутеров.",
       "На очень высоких частотах опроса (8000 Гц) слишком короткая очередь может привести к пропуску событий. Если курсор задёргался — откатите."),
      ("Shrink the mouse buffer",
       "The mouse driver queues up to 100 packets before handing them over. Setting 20 shortens that queue, so movement reaches the game sooner with less buffering. One of the key Atlas tweaks for competitive shooters.",
       "At very high polling rates (8000 Hz) too short a queue can drop events. Revert if the cursor starts stuttering."),
      [R("HKLM", MOUSE, "MouseDataQueueSize", "dword", 20, 100)],
      tags=["input", "latency"], src="atlas", restart=True),

    T("input.keyboard-queue", "input", "advanced",
      ("Уменьшить буфер клавиатуры",
       "То же самое для клавиатуры: очередь драйвера сокращается со 100 позиций до 20, нажатия доходят до приложения с меньшей задержкой.",
       None),
      ("Shrink the keyboard buffer",
       "The same for the keyboard: the driver queue drops from 100 slots to 20, so key presses reach the app with less delay.",
       None),
      [R("HKLM", KBD, "KeyboardDataQueueSize", "dword", 20, 100)],
      tags=["input", "latency"], src="atlas", restart=True),

    T("input.foreground-lock", "input", "safe",
      ("Мгновенное переключение фокуса",
       "Windows держит блокировку переднего плана 200 миллисекунд, чтобы окна не воровали фокус друг у друга. Из-за этого Alt+Tab в игру иногда срабатывает с задержкой. Ноль убирает паузу.",
       None),
      ("Instant focus switching",
       "Windows holds a 200 ms foreground lock so windows cannot steal focus from each other. It makes Alt+Tab into a game feel delayed. Zero removes the pause.",
       None),
      [R("HKCU", r"Control Panel\Desktop", "ForegroundLockTimeout", "dword", 0, 200000)],
      tags=["input", "ui"], logoff=True),

    T("input.numlock-on", "input", "safe",
      ("Включать NumLock при загрузке",
       "Цифровой блок включается сразу на экране входа, а не после ручного нажатия.",
       None),
      ("NumLock on at boot",
       "The number pad is enabled right at the sign-in screen instead of after a manual press.",
       None),
      [R("HKU", r".DEFAULT\Control Panel\Keyboard", "InitialKeyboardIndicators", "sz", "2", "2147483648"),
       R("HKCU", r"Control Panel\Keyboard", "InitialKeyboardIndicators", "sz", "2", "2147483648")],
      tags=["input"]),

    T("perf.ndu-off", "performance", "advanced",
      ("Отключить драйвер учёта трафика",
       "Ndu — драйвер уровня ядра, который считает трафик по приложениям для диспетчера задач. Он сидит в сетевом стеке и на части систем добавляет заметную задержку и утечку памяти.",
       "Вкладка «Сеть» в диспетчере задач перестанет показывать потребление трафика по приложениям."),
      ("Disable the network usage driver",
       "Ndu is a kernel driver that counts per-app traffic for Task Manager. It sits in the network stack and on some systems adds measurable latency and a memory leak.",
       "The Network column in Task Manager will stop showing per-app traffic."),
      [R("HKLM", CCS + r"\Services\Ndu", "Start", "dword", 4, 2)],
      tags=["network", "latency", "ram"], src="atlas", restart=True),

    T("perf.paging-combining-off", "performance", "advanced",
      ("Отключить объединение страниц памяти",
       "Windows ищет одинаковые страницы памяти и склеивает их, экономя объём ценой постоянной работы процессора по сравнению страниц. При большом объёме памяти экономия не нужна.",
       "На системах с 8 ГБ и меньше вырастет расход памяти."),
      ("Disable memory page combining",
       "Windows scans for identical memory pages and merges them, saving space at the cost of constant CPU work comparing pages. With plenty of RAM the saving is pointless.",
       "On systems with 8 GB or less memory usage will grow."),
      [R("HKLM", MM, "DisablePagingCombining", "dword", 1, 0)],
      tags=["ram", "cpu"], src="atlas", restart=True),

    T("perf.maintenance-off", "performance", "advanced",
      ("Отключить автоматическое обслуживание",
       "Ночью Windows сама запускает дефрагментацию, проверку обновлений, диагностику и сканирование. Если компьютер в это время работает, обслуживание внезапно занимает диск и процессор.",
       "Плановые проверки диска и обновление определений перестанут запускаться сами."),
      ("Disable automatic maintenance",
       "At night Windows runs defrag, update checks, diagnostics and scans on its own. If the PC is in use at that moment, maintenance suddenly takes over disk and CPU.",
       "Scheduled disk checks and definition updates will stop running by themselves."),
      [R("HKLM", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\Maintenance", "MaintenanceDisabled", "dword", 1, 0)],
      tags=["cpu", "disk"], src="atlas"),

    T("perf.timer-resolution", "performance", "advanced",
      ("Глобальное разрешение таймера",
       "С Windows 11 22H2 запрошенное приложением разрешение таймера действует только на это приложение. Значение 1 возвращает прежнее поведение, когда запрос игры распространяется на всю систему.",
       None),
      ("Global timer resolution",
       "Since Windows 11 22H2 a requested timer resolution applies only to the requesting app. Setting 1 restores the old behaviour where a game's request covers the whole system.",
       None),
      [R("HKLM", CCS + r"\Control\Session Manager\kernel", "GlobalTimerResolutionRequests", "dword", 1, 0)],
      tags=["latency", "fps"], src="atlas", req="b22h2", restart=True),

    T("perf.crash-dump-small", "performance", "safe",
      ("Уменьшить дамп при синем экране",
       "Полный дамп памяти при сбое пишет на диск объём, равный оперативной памяти. Малый дамп занимает мегабайты и для диагностики обычно достаточен.",
       None),
      ("Smaller crash dump",
       "A complete memory dump writes as much to disk as you have RAM. A small dump takes megabytes and is usually enough to diagnose a crash.",
       None),
      [R("HKLM", CCS + r"\Control\CrashControl", "CrashDumpEnabled", "dword", 3, 7),
       R("HKLM", CCS + r"\Control\CrashControl", "AlwaysKeepMemoryDump", "dword", 0, 0)],
      tags=["disk"]),

    T("game.gamebar-presence-off", "gaming", "advanced",
      ("Убрать GameBarPresenceWriter",
       "Отдельный фоновый процесс игровой панели, который остаётся в памяти даже после отключения самой панели и переживает обновления.",
       None),
      ("Remove GameBarPresenceWriter",
       "A separate Game Bar background process that stays in memory even after the bar itself is disabled and survives updates.",
       None),
      [R("HKLM", r"SOFTWARE\Microsoft\WindowsRuntime\ActivatableClassId\Windows.Gaming.GameBar.PresenceServer.Internal.PresenceWriter", "ActivationType", "dword", 0, 1)],
      tags=["ram", "fps"], src="atlas"),

    T("priv.office-telemetry", "privacy", "safe",
      ("Отключить телеметрию Office",
       "Microsoft Office отправляет статистику использования, данные о документах и отчёты о сбоях. Политики переводят уровень диагностики в минимальный и отключают подключённые службы.",
       None),
      ("Disable Office telemetry",
       "Microsoft Office sends usage statistics, document data and crash reports. These policies set diagnostics to the minimum and turn off connected services.",
       None),
      [R("HKCU", r"Software\Policies\Microsoft\office\common\clienttelemetry", "sendtelemetry", "dword", 3, 1),
       R("HKCU", r"Software\Policies\Microsoft\office\common\clienttelemetry", "disableTelemetry", "dword", 1, 0),
       R("HKCU", OFFPOL, "sendcustomerdata", "dword", 0, 1),
       R("HKCU", OFFPOL, "qmenable", "dword", 0, 1),
       R("HKCU", OFFPOL + r"\privacy", "disconnectedstate", "dword", 2, 0),
       R("HKCU", OFFPOL + r"\privacy", "usercontentdisabled", "dword", 2, 0),
       R("HKCU", OFFPOL + r"\privacy", "downloadcontentdisabled", "dword", 2, 0),
       R("HKCU", OFFPOL + r"\privacy", "controllerconnectedservicesenabled", "dword", 2, 1)],
      tags=["privacy"]),

    T("priv.office-feedback", "privacy", "safe",
      ("Убрать отзывы и смайлики Office",
       "Кнопки «Отправить улыбку» и «Отправить хмурое лицо» на ленте, сбор отчётов Watson и предложение оценить работу программы.",
       None),
      ("Remove Office feedback prompts",
       "The smiley and frowny feedback buttons on the ribbon, Watson report collection and the rate-us prompt.",
       None),
      [R("HKCU", OFF16 + r"\Feedback", "Enabled", "dword", 0, 1),
       R("HKCU", OFF16 + r"\Feedback", "IncludeEmail", "dword", 0, 1),
       R("HKCU", OFF16 + r"\PTWatson", "PTWOptIn", "dword", 0, 1),
       R("HKCU", OFF16 + r"\General", "ShownFirstRunOptin", "dword", 1, 0)],
      tags=["privacy", "ui"]),

    T("priv.ink-workspace-off", "privacy", "safe",
      ("Отключить рабочую область Windows Ink",
       "Панель рукописного ввода с блокнотом и набросками. Нужна только на устройствах с пером.",
       None),
      ("Disable Windows Ink Workspace",
       "The pen workspace with sticky notes and sketchpad. Only useful on devices with a stylus.",
       None),
      [R("HKLM", r"SOFTWARE\Policies\Microsoft\WindowsInkWorkspace", "AllowWindowsInkWorkspace", "dword", 0, 1),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\WindowsInkWorkspace", "AllowSuggestedAppsInWindowsInkWorkspace", "dword", 0, 1)],
      tags=["ui", "ram"]),

    T("ui.sync-ads-off", "interface", "safe",
      ("Убрать рекламу OneDrive из проводника",
       "«Уведомления поставщика синхронизации» — это баннеры Microsoft прямо в окне проводника, предлагающие OneDrive и подписку. К реальной синхронизации файлов они отношения не имеют.",
       None),
      ("Remove OneDrive ads from Explorer",
       "Sync provider notifications are Microsoft banners inside the Explorer window pushing OneDrive and subscriptions. They have nothing to do with actual file syncing.",
       None),
      [R("HKCU", ADV, "ShowSyncProviderNotifications", "dword", 0, 1)],
      tags=["ui", "privacy"], logoff=True),

    T("ui.folder-type-off", "interface", "advanced",
      ("Одинаковый вид всех папок",
       "Проводник пытается угадать содержимое папки и переключает её в режим «Изображения» или «Музыка», меняя колонки и замедляя открытие. Жёсткий режим «Общие элементы» убирает и угадывание, и задержку.",
       "Папки с фотографиями перестанут автоматически показывать эскизы вместо списка."),
      ("Same view for every folder",
       "Explorer guesses folder contents and switches to Pictures or Music mode, changing columns and slowing the folder down. Forcing General items removes both the guessing and the delay.",
       "Photo folders will stop switching to thumbnails automatically."),
      [R("HKCU", r"Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell", "FolderType", "sz", "NotSpecified", "Documents")],
      tags=["ui", "disk"], logoff=True),

    T("ui.taskbar-hover-fast", "interface", "safe",
      ("Ускорить превью на панели задач",
       "Миниатюра окна появляется через 400 мс после наведения. Сотня миллисекунд делает панель задач заметно отзывчивее.",
       None),
      ("Faster taskbar previews",
       "The window thumbnail appears 400 ms after hover. A hundred milliseconds makes the taskbar feel noticeably snappier.",
       None),
      [R("HKCU", ADV, "ExtendedUIHoverTime", "dword", 100, 400)],
      tags=["ui"], logoff=True),

    T("ui.meet-now-off", "interface", "safe",
      ("Убрать «Собрание» из трея",
       "Иконка Skype Meet Now рядом с часами, которую Microsoft добавила обновлением.",
       None),
      ("Remove Meet Now from the tray",
       "The Skype Meet Now icon next to the clock that Microsoft added in an update.",
       None),
      [R("HKLM", CV + r"\Policies\Explorer", "HideSCAMeetNow", "dword", 1, 0),
       R("HKCU", CVU + r"\Policies\Explorer", "HideSCAMeetNow", "dword", 1, 0)],
      tags=["ui"], logoff=True),

    T("ui.3d-objects-off", "interface", "safe",
      ("Убрать «Объёмные объекты» из проводника",
       "Папка «Объёмные объекты» в разделе «Этот компьютер», которой почти никто не пользуется.",
       None),
      ("Remove 3D Objects from Explorer",
       "The 3D Objects folder under This PC that almost nobody uses.",
       None),
      [RD("HKLM", CV + r"\Explorer\MyComputer\NameSpace\{0DB7E03F-FC29-4DC6-9020-FF41B59E513A}"),
       RD("HKLM", r"SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{0DB7E03F-FC29-4DC6-9020-FF41B59E513A}")],
      tags=["ui"], req="win10", logoff=True),

    T("ui.default-printer-manual", "interface", "safe",
      ("Не менять принтер по умолчанию самому",
       "Windows назначает принтером по умолчанию тот, на котором печатали последним. Если принтеров несколько, документы регулярно уходят не туда.",
       None),
      ("Stop Windows managing the default printer",
       "Windows makes the last used printer the default. With several printers documents regularly go to the wrong one.",
       None),
      [R("HKCU", r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows", "LegacyDefaultPrinterMode", "dword", 1, 0)],
      tags=["ui"]),

    T("ui.shortcut-arrow-off", "interface", "safe",
      ("Убрать стрелку с ярлыков",
       "Маленькая стрелка в углу иконок ярлыков. Значок остаётся ярлыком, меняется только оформление.",
       None),
      ("Remove the shortcut arrow overlay",
       "The little arrow in the corner of shortcut icons. The icon stays a shortcut, only the overlay changes.",
       None),
      [R("HKLM", CV + r"\Explorer\Shell Icons", "29", "sz", "%windir%\\System32\\shell32.dll,-50", "")],
      tags=["ui"], logoff=True),

    T("net.netbios-off", "network", "advanced",
      ("Отключить NetBIOS над TCP/IP",
       "Протокол времён Windows 98 для поиска компьютеров в локальной сети. Сейчас используется в основном для перехвата учётных данных, а имена резолвятся через DNS.",
       "Доступ к очень старым сетевым папкам по коротким именам может перестать работать."),
      ("Disable NetBIOS over TCP/IP",
       "A Windows 98 era protocol for finding computers on the LAN. Nowadays it is mostly used for credential interception while names resolve through DNS.",
       "Access to very old network shares by short name may stop working."),
      [PS("Get-ChildItem 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\NetBT\\Parameters\\Interfaces' | ForEach-Object { Set-ItemProperty -Path $_.PSPath -Name NetbiosOptions -Value 2 -Type DWord -Force }",
          "Get-ChildItem 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\NetBT\\Parameters\\Interfaces' | ForEach-Object { Set-ItemProperty -Path $_.PSPath -Name NetbiosOptions -Value 0 -Type DWord -Force }"),
       SV("lmhosts", "disabled", "manual")],
      tags=["network", "security"], restart=True),

    T("disk.ntfs-memory", "disk", "advanced",
      ("Увеличить память под таблицу файлов",
       "NTFS держит в памяти кэш метаданных фиксированного размера. На разделах с сотнями тысяч файлов увеличенный кэш заметно ускоряет открытие папок и поиск.",
       None),
      ("More memory for the file table",
       "NTFS keeps a fixed-size metadata cache in memory. On volumes with hundreds of thousands of files a larger cache speeds up folder opening and search.",
       None),
      [R("HKLM", CCS + r"\Control\FileSystem", "NtfsMemoryUsage", "dword", 2, 0)],
      tags=["disk"], restart=True),

    T("svc.superfetch-hdd", "services", "safe",
      ("Оставить SysMain на жёстком диске",
       "Если система стоит на HDD, SysMain действительно ускоряет запуск программ, подгружая их заранее. Твик возвращает службу в автозапуск, если её отключили по ошибке.",
       None),
      ("Keep SysMain on a hard drive",
       "If Windows runs from an HDD, SysMain genuinely speeds up app launches by preloading them. This returns the service to automatic start if it was disabled by mistake.",
       None),
      [SV("SysMain", "auto", "auto", stop=False)],
      tags=["disk"], req="hdd"),

    T("sec.uac-max", "security", "safe",
      ("Максимальный уровень UAC",
       "Запрос подтверждения при любой попытке программы изменить систему, включая изменения настроек самой Windows. Самый строгий из штатных уровней.",
       None),
      ("Maximum UAC level",
       "Prompt on every attempt to change the system, including Windows settings changes. The strictest built-in level.",
       None),
      [R("HKLM", CV + r"\Policies\System", "ConsentPromptBehaviorAdmin", "dword", 2, 5),
       R("HKLM", CV + r"\Policies\System", "PromptOnSecureDesktop", "dword", 1, 1),
       R("HKLM", CV + r"\Policies\System", "EnableLUA", "dword", 1, 1)],
      tags=["security"]),

    T("priv.error-reporting-queue", "privacy", "safe",
      ("Не копить отчёты об ошибках",
       "Очередь Windows Error Reporting хранит дампы упавших программ на диске до отправки. Отключение очереди убирает и накопление файлов, и отправку.",
       None),
      ("Stop queuing error reports",
       "The Windows Error Reporting queue stores crash dumps on disk until they are sent. Disabling it removes both the files and the upload.",
       None),
      [R("HKCU", CVU + r"\Windows Error Reporting", "DontShowUI", "dword", 1, 0),
       R("HKLM", r"SOFTWARE\Microsoft\Windows\Windows Error Reporting", "DontSendAdditionalData", "dword", 1, 0),
       R("HKLM", r"SOFTWARE\Microsoft\Windows\Windows Error Reporting\Consent", "DefaultConsent", "dword", 1, 1)],
      tags=["privacy", "disk"]),
]
