from tw_common import *

ITEMS = [
    T("perf.priority-separation", "performance", "advanced",
      ("Приоритет активного окна",
       "Планировщик Windows делит процессорное время между окном, в котором вы работаете, и фоном. По умолчанию перекос в сторону фона небольшой. Значение 0x26 отдаёт активному приложению заметно больше квантов времени — в играх и тяжёлых программах это убирает часть микрофризов.",
       "На слабых процессорах фоновые задачи (распаковка, компиляция, торренты) начнут выполняться медленнее, пока активно другое окно."),
      ("Foreground window priority",
       "The Windows scheduler splits CPU time between the focused window and background work. Setting 0x26 gives the active app noticeably longer time slices, which removes part of the micro-stutter in games and heavy apps.",
       "On weak CPUs background work slows down while another window has focus."),
      [R("HKLM", CCS + r"\Control\PriorityControl", "Win32PrioritySeparation", "dword", 38, 2)],
      tags=["fps", "latency"], src="atlas"),

    T("perf.system-responsiveness", "performance", "advanced",
      ("Резерв CPU под мультимедиа",
       "MMCSS по умолчанию резервирует 20% процессора под мультимедийные задачи и отдаёт их остальным процессам в последнюю очередь. Для игрового ПК резерв не нужен — значение 0 возвращает эти проценты в общий пул.",
       None),
      ("Multimedia CPU reserve",
       "MMCSS reserves 20% of the CPU for multimedia tasks by default. On a gaming PC this reserve is not needed and 0 returns it to the common pool.",
       None),
      [R("HKLM", MMPROF, "SystemResponsiveness", "dword", 0, 20)],
      tags=["fps", "latency"], src="atlas"),

    T("perf.network-throttling", "performance", "advanced",
      ("Снять сетевой троттлинг",
       "Windows ограничивает обработку сетевых пакетов десятью тысячами в секунду, чтобы мультимедиа не захлебнулось. На гигабитном канале и в онлайн-играх этот лимит только мешает — значение 0xFFFFFFFF снимает его полностью.",
       None),
      ("Disable network throttling",
       "Windows caps network packet processing at 10000 per second so multimedia keeps priority. On gigabit links and in online games the cap only hurts; 0xFFFFFFFF removes it.",
       None),
      [R("HKLM", MMPROF, "NetworkThrottlingIndex", "dword", "0xFFFFFFFF", 10)],
      tags=["network", "latency"], src="atlas"),

    T("perf.games-task", "performance", "advanced",
      ("Профиль MMCSS для игр",
       "Ветка Tasks\\Games описывает, какой приоритет получает игра у планировщика и у подсистемы ввода-вывода. Значения по умолчанию рассчитаны на офисный ПК; здесь выставляется максимальный игровой профиль.",
       None),
      ("MMCSS profile for games",
       "The Tasks\\Games branch tells the scheduler and the I/O subsystem what priority a game gets. Defaults target an office PC; this sets the full gaming profile.",
       None),
      [R("HKLM", MMPROF + r"\Tasks\Games", "GPU Priority", "dword", 8, 8),
       R("HKLM", MMPROF + r"\Tasks\Games", "Priority", "dword", 6, 2),
       R("HKLM", MMPROF + r"\Tasks\Games", "Scheduling Category", "sz", "High", "Medium"),
       R("HKLM", MMPROF + r"\Tasks\Games", "SFIO Priority", "sz", "High", "Normal")],
      tags=["fps"], src="atlas"),

    T("perf.menu-delay", "performance", "safe",
      ("Убрать задержку меню",
       "Между наведением на пункт меню и его раскрытием Windows ждёт 400 мс. Это чистая анимационная пауза, интерфейс после её снятия ощущается заметно быстрее.",
       None),
      ("Remove menu delay",
       "Windows waits 400 ms before opening a hovered menu. Removing that pause makes the whole interface feel faster.",
       None),
      [R("HKCU", r"Control Panel\Desktop", "MenuShowDelay", "sz", "0", "400")],
      tags=["ui"], logoff=True),

    T("perf.startup-delay", "performance", "safe",
      ("Убрать задержку автозагрузки",
       "Windows специально придерживает программы из автозагрузки на несколько секунд после появления рабочего стола. Отключение убирает эту паузу — программы стартуют сразу.",
       None),
      ("Remove startup delay",
       "Windows deliberately holds startup apps back for several seconds after the desktop appears. This removes that pause.",
       None),
      [R("HKCU", CVU + r"\Explorer\Serialize", "StartupDelayInMSec", "dword", 0, 0)],
      tags=["boot"]),

    T("perf.mouse-accel", "performance", "safe",
      ("Отключить акселерацию мыши",
       "«Повышенная точность указателя» меняет пройденное курсором расстояние в зависимости от скорости движения руки. В шутерах это ломает мышечную память: одно и то же движение даёт разный поворот.",
       None),
      ("Disable mouse acceleration",
       "Enhanced pointer precision changes cursor distance based on how fast you move the mouse. In shooters it breaks muscle memory: the same movement gives a different turn.",
       None),
      [R("HKCU", r"Control Panel\Mouse", "MouseSpeed", "sz", "0", "1"),
       R("HKCU", r"Control Panel\Mouse", "MouseThreshold1", "sz", "0", "6"),
       R("HKCU", r"Control Panel\Mouse", "MouseThreshold2", "sz", "0", "10")],
      tags=["input", "fps"], logoff=True),

    T("perf.keyboard-speed", "performance", "safe",
      ("Ускорить повтор клавиш",
       "Минимальная задержка перед автоповтором и максимальная частота повтора. Заметно при навигации стрелками и в текстовых редакторах.",
       None),
      ("Faster key repeat",
       "Minimum delay before auto-repeat and maximum repeat rate. Noticeable when navigating with arrows and in text editors.",
       None),
      [R("HKCU", r"Control Panel\Keyboard", "KeyboardDelay", "sz", "0", "1"),
       R("HKCU", r"Control Panel\Keyboard", "KeyboardSpeed", "sz", "31", "31")],
      tags=["input"], logoff=True),

    T("perf.fast-startup-off", "performance", "safe",
      ("Отключить быстрый запуск",
       "Быстрый запуск сохраняет ядро и драйверы в файл гибернации вместо полной выгрузки. Из-за этого драйверы неделями не перезагружаются, накапливаются утечки, а часть проблем «лечится только перезагрузкой». Полноценное выключение становится чуть дольше, зато система каждый раз стартует с чистого состояния.",
       None),
      ("Disable Fast Startup",
       "Fast Startup hibernates the kernel and drivers instead of unloading them. Drivers then go weeks without a real restart and leaks accumulate. Shutdown gets slightly slower but the system starts clean every time.",
       None),
      [R("HKLM", CCS + r"\Control\Session Manager\Power", "HiberbootEnabled", "dword", 0, 1)],
      tags=["boot", "stability"], src="atlas", restart=True),

    T("perf.power-throttling-off", "performance", "advanced",
      ("Отключить Power Throttling",
       "Windows принудительно замедляет фоновые процессы ради экономии энергии. На стационарном ПК смысла в этом нет, а свёрнутые приложения и серверы игр от этого страдают.",
       "На ноутбуке без зарядки это заметно сократит время работы от батареи."),
      ("Disable Power Throttling",
       "Windows slows background processes down to save power. On a desktop this has no upside and hurts minimised apps and game servers.",
       "On a laptop running on battery this will noticeably cut battery life."),
      [R("HKLM", CCS + r"\Control\Power\PowerThrottling", "PowerThrottlingOff", "dword", 1, 0)],
      tags=["fps", "power"], src="atlas", restart=True),

    T("perf.paging-executive", "performance", "advanced",
      ("Держать ядро в оперативной памяти",
       "Запрещает выгружать код ядра и драйверов в файл подкачки. На машинах с 16 ГБ и больше это убирает микрозадержки при обращении к драйверам.",
       "На системах с 8 ГБ и меньше может наоборот привести к нехватке памяти."),
      ("Keep the kernel in RAM",
       "Stops kernel and driver code from being paged out. On 16 GB+ machines this removes micro-latency when drivers are touched.",
       "On systems with 8 GB or less this can cause memory pressure instead."),
      [R("HKLM", MM, "DisablePagingExecutive", "dword", 1, 0)],
      tags=["latency"], src="atlas", restart=True),

    T("perf.clear-pagefile-off", "performance", "safe",
      ("Не очищать файл подкачки при выключении",
       "Обнуление pagefile.sys при каждом выключении добавляет десятки секунд к завершению работы и нужно только там, где важна защита от анализа диска.",
       None),
      ("Do not clear the page file on shutdown",
       "Zeroing pagefile.sys on every shutdown adds tens of seconds and only matters where disk forensics is a concern.",
       None),
      [R("HKLM", MM, "ClearPageFileAtShutdown", "dword", 0, 0)],
      tags=["boot"]),

    T("perf.ntfs-lastaccess", "performance", "safe",
      ("Не писать время последнего доступа к файлам",
       "NTFS обновляет отметку «последний доступ» при каждом чтении файла — это лишние записи на диск при любой операции с большим количеством файлов.",
       None),
      ("Stop writing last access time",
       "NTFS updates the last-access timestamp on every file read, which means extra writes on any bulk file operation.",
       None),
      [R("HKLM", CCS + r"\Control\FileSystem", "NtfsDisableLastAccessUpdate", "dword", 1, "0x80000002")],
      tags=["disk"], src="atlas"),

    T("perf.8dot3-off", "performance", "advanced",
      ("Отключить короткие имена 8.3",
       "Для совместимости с MS-DOS NTFS создаёт второе, короткое имя для каждого файла. На разделах с сотнями тысяч файлов это заметно замедляет операции с каталогами.",
       "Очень старые установщики и программы, обращающиеся к путям вида PROGRA~1, могут перестать работать."),
      ("Disable 8.3 short names",
       "For MS-DOS compatibility NTFS creates a second short name for every file. On volumes with hundreds of thousands of files this slows directory operations.",
       "Very old installers that rely on PROGRA~1 style paths may break."),
      [R("HKLM", CCS + r"\Control\FileSystem", "NtfsDisable8dot3NameCreation", "dword", 1, 2)],
      tags=["disk"], src="atlas"),

    T("perf.mem-compression-off", "performance", "advanced",
      ("Отключить сжатие памяти",
       "Windows сжимает неиспользуемые страницы памяти вместо выгрузки на диск, тратя на это процессор. При 32 ГБ и больше компрессия почти не нужна, а нагрузка на CPU остаётся.",
       "При 8-16 ГБ памяти отключение приведёт к более частому обращению к файлу подкачки."),
      ("Disable memory compression",
       "Windows compresses cold memory pages instead of paging them out, spending CPU on it. With 32 GB or more the compression is rarely needed while the CPU cost stays.",
       "With 8-16 GB of RAM this leads to more page file activity."),
      [PS("Disable-MMAgent -mc", "Enable-MMAgent -mc")],
      tags=["ram"], src="atlas", restart=True),

    T("perf.sysmain-off", "performance", "advanced",
      ("Отключить SysMain (Superfetch)",
       "SysMain заранее подгружает в память часто используемые программы. На жёстком диске это ускоряет запуск, на SSD выигрыш нулевой, а фоновые чтения и нагрузка на диск остаются.",
       None),
      ("Disable SysMain (Superfetch)",
       "SysMain preloads frequently used apps into RAM. On a hard drive that helps; on an SSD the gain is zero while the background reads remain.",
       None),
      [SV("SysMain", "disabled", "auto")],
      tags=["disk", "ram"], src="atlas", req="ssd"),

    T("perf.search-index-off", "performance", "advanced",
      ("Отключить индексацию поиска",
       "Служба Windows Search постоянно перечитывает файлы, чтобы поиск в проводнике был мгновенным. Если вы ищете через Everything или вообще не пользуетесь поиском по содержимому, служба только ест диск и процессор.",
       "Поиск в проводнике и в меню Пуск станет медленным перебором файлов."),
      ("Disable search indexing",
       "Windows Search constantly re-reads files so Explorer search is instant. If you use Everything or rarely search by content, the service only eats disk and CPU.",
       "Explorer and Start menu search will fall back to slow file scanning."),
      [SV("WSearch", "disabled", "delayed")],
      tags=["disk", "cpu"]),

    T("perf.prefetch-off", "performance", "advanced",
      ("Отключить Prefetch и Superfetch",
       "Сбор статистики запусков для предзагрузки. На SSD выигрыш в скорости старта нулевой, а служба продолжает писать на диск.",
       None),
      ("Disable Prefetch and Superfetch",
       "Launch statistics used for preloading. On an SSD the startup gain is zero while the service keeps writing to disk.",
       None),
      [R("HKLM", MM + r"\PrefetchParameters", "EnablePrefetcher", "dword", 0, 3),
       R("HKLM", MM + r"\PrefetchParameters", "EnableSuperfetch", "dword", 0, 3)],
      tags=["disk"], req="ssd", restart=True),

    T("perf.svchost-split", "performance", "advanced",
      ("Объединить процессы svchost",
       "На системах с большим объёмом памяти Windows запускает каждую службу в отдельном процессе — это десятки лишних svchost.exe. Объединение в общие группы освобождает сотни мегабайт и сокращает список процессов.",
       None),
      ("Group svchost processes",
       "On machines with plenty of RAM Windows runs each service in its own process, which means dozens of extra svchost.exe. Grouping them frees hundreds of megabytes.",
       None),
      [R("HKLM", CCS + r"\Control", "SvcHostSplitThresholdInKB", "dword", "0x4000000", "0x380000")],
      tags=["ram"], src="atlas", restart=True),

    T("perf.wer-off", "performance", "safe",
      ("Отключить отчёты об ошибках",
       "Windows Error Reporting собирает дампы упавших программ и отправляет их в Microsoft. Отключение убирает фоновую службу, очередь дампов и задержку при падении приложений.",
       None),
      ("Disable Windows Error Reporting",
       "WER collects crash dumps and sends them to Microsoft. Disabling it removes the background service, the dump queue and the pause when an app crashes.",
       None),
      [R("HKLM", r"SOFTWARE\Microsoft\Windows\Windows Error Reporting", "Disabled", "dword", 1, 0),
       R("HKLM", POL + r"\Windows Error Reporting", "Disabled", "dword", 1, 0),
       SV("WerSvc", "disabled", "manual")],
      tags=["privacy"], src="atlas"),

    T("perf.kill-timeouts", "performance", "safe",
      ("Сократить ожидание зависших программ",
       "При завершении работы Windows ждёт зависшие приложения по умолчанию 5 секунд и службы 5 секунд. Сокращение таймаутов ускоряет выключение и закрытие зависших окон.",
       "Программа, которая долго сохраняет данные при закрытии, может не успеть это сделать."),
      ("Shorter hung app timeouts",
       "On shutdown Windows waits 5 seconds for hung apps and services. Shorter timeouts speed up shutdown and closing frozen windows.",
       "An app that saves data slowly on exit may not finish."),
      [R("HKCU", r"Control Panel\Desktop", "AutoEndTasks", "sz", "1", "0"),
       R("HKCU", r"Control Panel\Desktop", "HungAppTimeout", "sz", "2000", "5000"),
       R("HKCU", r"Control Panel\Desktop", "WaitToKillAppTimeout", "sz", "3000", "5000"),
       R("HKLM", CCS + r"\Control", "WaitToKillServiceTimeout", "sz", "3000", "5000")],
      tags=["boot"]),

    T("perf.hibernate-off", "performance", "advanced",
      ("Отключить гибернацию",
       "Удаляет hiberfil.sys — файл размером примерно с объём оперативной памяти. На 32 ГБ это освобождает около 12-25 ГБ на системном диске.",
       "Спящий режим и быстрый запуск перестанут работать."),
      ("Disable hibernation",
       "Removes hiberfil.sys, a file roughly the size of your RAM. On 32 GB that frees about 12-25 GB on the system drive.",
       "Hibernate and Fast Startup stop working."),
      [CM("powercfg.exe", "/hibernate off", "/hibernate on")],
      tags=["disk"], req="desktop"),

    T("perf.mitigations-off", "performance", "extreme",
      ("Отключить защиту от Spectre и Meltdown",
       "Программные заплатки против аппаратных уязвимостей процессоров стоят от 5 до 15 процентов производительности, особенно на процессорах до 2019 года. Отключение возвращает эту производительность.",
       "Система становится уязвима к атакам по побочным каналам. Не делайте этого на рабочем компьютере, где обрабатываются чужие данные."),
      ("Disable Spectre and Meltdown mitigations",
       "Software patches for CPU hardware flaws cost 5 to 15 percent of performance, especially on pre-2019 CPUs. Disabling them returns that performance.",
       "The system becomes vulnerable to side-channel attacks. Do not do this on a work machine that handles other people's data."),
      [R("HKLM", MM, "FeatureSettingsOverride", "dword", 3, 0),
       R("HKLM", MM, "FeatureSettingsOverrideMask", "dword", 3, 3)],
      tags=["cpu", "fps"], src="atlas", restart=True),

    T("perf.dynamic-tick-off", "performance", "extreme",
      ("Отключить динамический тик таймера",
       "Динамический тик позволяет процессору дольше спать между прерываниями таймера. Для игр это означает менее стабильный интервал кадров; отключение делает тайминги ровнее ценой энергопотребления.",
       "На ноутбуке заметно вырастет расход батареи. На некоторых конфигурациях может увеличиться потребление в простое."),
      ("Disable dynamic timer tick",
       "Dynamic tick lets the CPU sleep longer between timer interrupts. For games that means less even frame pacing; disabling it smooths timings at the cost of power.",
       "On a laptop battery drain grows noticeably. Idle power use may rise on some systems."),
      [CM("bcdedit.exe", "/set disabledynamictick yes", "/set disabledynamictick no")],
      tags=["latency"], src="atlas", req="desktop", restart=True),

    T("perf.tsc-sync", "performance", "extreme",
      ("Синхронизация TSC между ядрами",
       "Режим Enhanced заставляет Windows синхронизировать счётчик тактов между ядрами при старте. На многоядерных процессорах это убирает редкие скачки таймингов в играх.",
       "На отдельных конфигурациях может привести к сбоям при загрузке. Отключается тем же переключателем."),
      ("Enhanced TSC sync policy",
       "Enhanced mode makes Windows synchronise the timestamp counter across cores at boot. On many-core CPUs this removes rare timing spikes in games.",
       "On some configurations it can cause boot issues. Reverting uses the same switch."),
      [CM("bcdedit.exe", "/set tscsyncpolicy Enhanced", "/deletevalue tscsyncpolicy")],
      tags=["latency"], src="atlas", restart=True),

    T("game.gamedvr-off", "gaming", "safe",
      ("Отключить Game DVR",
       "Фоновая запись последних минут игры работает всегда, даже если вы ни разу не нажимали Win+Alt+R. Это стабильно стоит нескольких кадров в секунду и добавляет нагрузку на видеокарту.",
       None),
      ("Disable Game DVR",
       "Background recording of the last few minutes runs all the time, even if you never press Win+Alt+R. It reliably costs a few FPS and loads the GPU.",
       None),
      [R("HKCU", r"System\GameConfigStore", "GameDVR_Enabled", "dword", 0, 1),
       R("HKCU", r"System\GameConfigStore", "GameDVR_FSEBehaviorMode", "dword", 2, 2),
       R("HKCU", CVU + r"\GameDVR", "AppCaptureEnabled", "dword", 0, 1),
       R("HKLM", POL + r"\GameDVR", "AllowGameDVR", "dword", 0, 1)],
      tags=["fps", "gpu"], src="atlas"),

    T("game.gamebar-off", "gaming", "safe",
      ("Убрать игровую панель",
       "Оверлей Xbox Game Bar перехватывает Win+G, показывает всплывающие панели при запуске игр и держит в памяти несколько процессов.",
       None),
      ("Disable Xbox Game Bar",
       "The Game Bar overlay hooks Win+G, pops up panels when games start and keeps several processes in memory.",
       None),
      [R("HKCU", r"Software\Microsoft\GameBar", "UseNexusForGameBarEnabled", "dword", 0, 1),
       R("HKCU", r"Software\Microsoft\GameBar", "ShowStartupPanel", "dword", 0, 1),
       R("HKCU", CVU + r"\GameDVR", "AppCaptureEnabled", "dword", 0, 1),
       R("HKCU", r"System\GameConfigStore", "GameDVR_Enabled", "dword", 0, 1)],
      tags=["fps"]),

    T("game.gamemode-on", "gaming", "safe",
      ("Включить игровой режим",
       "Игровой режим Windows придерживает фоновые обновления и отдаёт игре приоритет у планировщика. На современных сборках работает корректно и стоит того, чтобы быть включённым.",
       None),
      ("Enable Game Mode",
       "Game Mode holds back background updates and prioritises the game in the scheduler. On current builds it behaves well and is worth keeping on.",
       None),
      [R("HKCU", r"Software\Microsoft\GameBar", "AutoGameModeEnabled", "dword", 1, 1),
       R("HKCU", r"Software\Microsoft\GameBar", "AllowAutoGameMode", "dword", 1, 1)],
      tags=["fps"]),

    T("game.fso-off", "gaming", "advanced",
      ("Отключить оптимизацию полноэкранного режима",
       "Windows подменяет настоящий полный экран окном без рамки. Это удобно для Alt+Tab, но добавляет один кадр задержки и мешает работе G-Sync и FreeSync в части игр.",
       "Переключение между окнами станет медленнее, а в некоторых играх может пропасть HDR."),
      ("Disable fullscreen optimizations",
       "Windows replaces true fullscreen with a borderless window. Handy for Alt+Tab but it adds a frame of latency and interferes with G-Sync and FreeSync in some games.",
       "Alt+Tab gets slower and HDR may stop working in some titles."),
      [R("HKCU", r"System\GameConfigStore", "GameDVR_DXGIHonorFSEWindowsCompatible", "dword", 1, 0),
       R("HKCU", r"System\GameConfigStore", "GameDVR_HonorUserFSEBehaviorMode", "dword", 1, 0),
       R("HKCU", r"System\GameConfigStore", "GameDVR_EFSEFeatureFlags", "dword", 0, 0)],
      tags=["fps", "latency"], src="atlas"),

    T("game.xbox-services-off", "gaming", "advanced",
      ("Отключить службы Xbox",
       "Четыре службы Xbox Live работают постоянно, даже если вы не играете в игры из Game Pass и не пользуетесь Microsoft Store.",
       "Игры из Game Pass, облачные сохранения Xbox и вход через учётную запись Xbox перестанут работать."),
      ("Disable Xbox services",
       "Four Xbox Live services run constantly even if you never touch Game Pass or the Microsoft Store.",
       "Game Pass titles, Xbox cloud saves and Xbox sign-in will stop working."),
      [SV("XblAuthManager", "disabled", "manual"),
       SV("XblGameSave", "disabled", "manual"),
       SV("XboxGipSvc", "disabled", "manual"),
       SV("XboxNetApiSvc", "disabled", "manual")],
      tags=["ram"]),

    T("gpu.hags-on", "gaming", "advanced",
      ("Аппаратное планирование GPU",
       "HAGS передаёт управление очередью команд видеокарте вместо процессора. На картах GTX 1000 и новее это немного снижает задержку и разгружает CPU. Нужна поддержка драйвера.",
       "На некоторых старых драйверах вызывает падения в OBS и в играх на DX11. Если появились вылеты — выключите обратно."),
      ("Hardware-accelerated GPU scheduling",
       "HAGS moves command queue management from the CPU to the GPU. On GTX 1000 and newer it slightly lowers latency and offloads the CPU. Driver support required.",
       "Some older drivers crash in OBS and DX11 games with it on. Revert if you see crashes."),
      [R("HKLM", CCS + r"\Control\GraphicsDrivers", "HwSchMode", "dword", 2, 1)],
      tags=["gpu", "latency"], restart=True),

    T("gpu.mpo-off", "gaming", "advanced",
      ("Отключить Multi-Plane Overlay",
       "MPO — оптимизация вывода нескольких слоёв изображения. На связке из нескольких мониторов и на части драйверов NVIDIA она вызывает мерцание, чёрные окна и подёргивания курсора. Отключение — известное лечение этих симптомов.",
       None),
      ("Disable Multi-Plane Overlay",
       "MPO is a multi-layer display optimisation. On multi-monitor setups and some NVIDIA drivers it causes flickering, black windows and cursor stutter. Disabling it is the known fix.",
       None),
      [R("HKLM", r"SOFTWARE\Microsoft\Windows\Dwm", "OverlayTestMode", "dword", 5)],
      tags=["gpu", "stability"], restart=True),

    T("gpu.tdr-delay", "gaming", "advanced",
      ("Увеличить таймаут драйвера видеокарты",
       "Если видеокарта не отвечает две секунды, Windows перезапускает драйвер и роняет игру. При разгоне или тяжёлом рендере двух секунд иногда мало — здесь таймаут поднимается до десяти.",
       "Настоящее зависание драйвера теперь будет держать систему дольше, прежде чем она восстановится."),
      ("Increase GPU driver timeout",
       "If the GPU stops responding for two seconds Windows resets the driver and kills the game. Under overclocking or heavy rendering two seconds is sometimes too little; this raises it to ten.",
       "A genuine driver hang will now freeze the system for longer before recovery."),
      [R("HKLM", CCS + r"\Control\GraphicsDrivers", "TdrDelay", "dword", 10, 2),
       R("HKLM", CCS + r"\Control\GraphicsDrivers", "TdrDdiDelay", "dword", 10, 5)],
      tags=["gpu", "stability"], restart=True),

    T("gpu.nvidia-telemetry", "gaming", "safe",
      ("Отключить телеметрию NVIDIA",
       "Драйвер NVIDIA ставит три задачи в планировщик и службу сбора статистики. Ни на драйвер, ни на игры они не влияют.",
       None),
      ("Disable NVIDIA telemetry",
       "The NVIDIA driver installs three scheduled tasks and a telemetry service. Neither the driver nor games depend on them.",
       None),
      [R("HKLM", r"SOFTWARE\NVIDIA Corporation\NvControlPanel2\Client", "OptInOrOutPreference", "dword", 0, 1),
       SV("NvTelemetryContainer", "disabled", "auto"),
       TK(r"\NvTmRep_CrashReport1_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}"),
       TK(r"\NvTmRep_CrashReport2_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}"),
       TK(r"\NvTmRep_CrashReport3_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}"),
       TK(r"\NvTmRep_CrashReport4_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}"),
       TK(r"\NvTmMon_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}"),
       TK(r"\NvTmRepOnLogon_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}")],
      tags=["privacy", "gpu"], req="nvidia"),

    T("pwr.high-performance", "power", "safe",
      ("Схема питания «Высокая производительность»",
       "Убирает понижение частоты процессора в простое и засыпание дисков. Самый простой способ избавиться от рывков в первые секунды нагрузки.",
       None),
      ("High performance power plan",
       "Stops the CPU from dropping frequency at idle and disks from spinning down. The simplest fix for stutter in the first seconds of load.",
       None),
      [CM("powercfg.exe", "/setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c",
          "/setactive 381b4222-f694-41f0-9685-ff5bb260df2e")],
      tags=["power", "fps"]),

    T("pwr.ultimate", "power", "advanced",
      ("Схема питания «Максимальная производительность»",
       "Скрытая схема Ultimate Performance: отключает все механизмы экономии, включая парковку ядер и задержки переключения состояний. Создаётся и активируется автоматически.",
       "Растёт энергопотребление и нагрев. Для ноутбука не подходит."),
      ("Ultimate Performance power plan",
       "The hidden Ultimate Performance scheme disables every power saving mechanism including core parking. It is created and activated automatically.",
       "Power draw and heat go up. Not suitable for laptops."),
      [CM("cmd.exe", "/c powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61 && powercfg /setactive e9a42b02-d5df-448d-aa00-03f14749eb61",
          "/c powercfg /setactive 381b4222-f694-41f0-9685-ff5bb260df2e")],
      tags=["power", "fps"], req="desktop"),

    T("pwr.core-parking-off", "power", "advanced",
      ("Отключить парковку ядер",
       "Windows усыпляет часть ядер в простое и будит их с задержкой в несколько миллисекунд. В играх с непостоянной нагрузкой это видно как редкие просадки.",
       "Процессор будет держать все ядра активными: выше потребление и температура в простое."),
      ("Disable core parking",
       "Windows parks idle cores and takes several milliseconds to wake them. In games with uneven load that shows up as occasional dips.",
       "All cores stay active: higher idle power draw and temperature."),
      [CM("cmd.exe", "/c powercfg -setacvalueindex scheme_current sub_processor CPMINCORES 100 && powercfg -setactive scheme_current",
          "/c powercfg -setacvalueindex scheme_current sub_processor CPMINCORES 5 && powercfg -setactive scheme_current")],
      tags=["fps", "latency"], src="atlas", req="desktop"),

    T("pwr.usb-suspend-off", "power", "advanced",
      ("Запретить отключение USB для экономии",
       "Выборочная приостановка USB усыпляет порты, из-за чего мышь и клавиатура иногда «просыпаются» с задержкой, а внешние диски отваливаются.",
       "На ноутбуке немного вырастет расход батареи."),
      ("Disable USB selective suspend",
       "USB selective suspend puts ports to sleep, which makes mice and keyboards wake with a delay and external drives disconnect.",
       "Slightly higher battery drain on laptops."),
      [CM("cmd.exe", "/c powercfg -setacvalueindex scheme_current 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 0 && powercfg -setactive scheme_current",
          "/c powercfg -setacvalueindex scheme_current 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 1 && powercfg -setactive scheme_current")],
      tags=["input", "power"]),

    T("pwr.disk-timeout-off", "power", "safe",
      ("Не усыплять жёсткие диски",
       "По умолчанию диск останавливается после 20 минут простоя. Пробуждение занимает несколько секунд, и в этот момент система подвисает.",
       None),
      ("Never spin down disks",
       "By default drives stop after 20 minutes idle. Spinning back up takes seconds and the system hangs meanwhile.",
       None),
      [CM("powercfg.exe", "-change -disk-timeout-ac 0", "-change -disk-timeout-ac 20")],
      tags=["disk"]),

    T("disk.defrag-ssd-off", "disk", "advanced",
      ("Отключить плановую дефрагментацию",
       "Для SSD Windows запускает не дефрагментацию, а ретрим, но задача всё равно будит диск по расписанию и раз в месяц запускает полную дефрагментацию, если решит, что это нужно.",
       None),
      ("Disable scheduled defrag",
       "On SSDs Windows runs retrim rather than defrag, but the task still wakes the drive on schedule and may run a full defrag monthly.",
       None),
      [TK(r"\Microsoft\Windows\Defrag\ScheduledDefrag")],
      tags=["disk"], req="ssd"),

    T("disk.trim-on", "disk", "safe",
      ("Включить TRIM",
       "TRIM сообщает SSD, какие блоки больше не используются. Без него скорость записи со временем падает. Проверяется и включается принудительно.",
       None),
      ("Enable TRIM",
       "TRIM tells the SSD which blocks are free. Without it write speed degrades over time. This checks and forces it on.",
       None),
      [CM("fsutil.exe", "behavior set DisableDeleteNotify 0", "behavior set DisableDeleteNotify 0")],
      tags=["disk"], req="ssd"),

    T("disk.storage-sense-off", "disk", "safe",
      ("Отключить контроль памяти",
       "Storage Sense сам удаляет файлы из корзины и папки загрузок по расписанию. Многие узнают об этом, когда файл уже удалён.",
       None),
      ("Disable Storage Sense",
       "Storage Sense deletes files from the Recycle Bin and Downloads on a schedule. Most people find out about it after a file is gone.",
       None),
      [R("HKCU", CVU + r"\StorageSense\Parameters\StoragePolicy", "01", "dword", 0, 1)],
      tags=["disk"]),

    T("disk.reserved-storage-off", "disk", "advanced",
      ("Отключить зарезервированное хранилище",
       "Windows держит 7-10 ГБ на системном диске под обновления. На небольшом SSD это заметная доля объёма.",
       "Крупные обновления Windows могут потребовать освобождения места вручную."),
      ("Disable reserved storage",
       "Windows keeps 7-10 GB on the system drive for updates. On a small SSD that is a noticeable share.",
       "Major Windows updates may require freeing space manually."),
      [CM("dism.exe", "/Online /Set-ReservedStorageState /State:Disabled",
          "/Online /Set-ReservedStorageState /State:Enabled")],
      tags=["disk"]),
]
