from tw_common import *

VFX = CVU + r"\Explorer\VisualEffects"
DEFPOL = r"SOFTWARE\Policies\Microsoft\Windows Defender"

ITEMS = [
    T("weak.visual-effects", "weak", "safe",
      ("Оформление на минимум",
       "Переводит все визуальные эффекты в режим «наилучшее быстродействие»: пропадают тени, плавное появление меню, анимация сворачивания и отрисовка содержимого окна при перетаскивании. На старой встроенной видеокарте это самая заметная прибавка к отзывчивости из всего, что вообще можно сделать.",
       "Windows будет выглядеть заметно проще и площе. Сглаживание шрифтов остаётся включённым, текст читается как обычно."),
      ("Visual effects to minimum",
       "Switches every visual effect to best performance: no shadows, no menu fades, no minimise animation, no window contents while dragging. On old integrated graphics this is the single most noticeable responsiveness gain available.",
       "Windows will look plainer and flatter. Font smoothing stays on, so text reads as usual."),
      [R("HKCU", VFX, "VisualFXSetting", "dword", 2, 0),
       R("HKCU", r"Control Panel\Desktop", "UserPreferencesMask", "binary", "9012038010000000", "9E3E078012000000"),
       R("HKCU", r"Control Panel\Desktop", "DragFullWindows", "sz", "0", "1"),
       R("HKCU", r"Control Panel\Desktop\WindowMetrics", "MinAnimate", "sz", "0", "1"),
       R("HKCU", ADV, "TaskbarAnimations", "dword", 0, 1),
       R("HKCU", ADV, "ListviewShadow", "dword", 0, 1),
       R("HKCU", CVU + r"\Themes\Personalize", "EnableTransparency", "dword", 0, 1)],
      tags=["ui", "fps", "gpu"], logoff=True),

    T("weak.icons-only", "weak", "advanced",
      ("Иконки вместо эскизов в проводнике",
       "Проводник перестаёт генерировать миниатюры для картинок и видео. На жёстком диске папка с фотографиями открывается мгновенно вместо нескольких секунд подгрузки, а слабая видеокарта не тратится на отрисовку превью.",
       "Вместо превью фотографий и видео будут обычные значки типа файла."),
      ("Icons instead of thumbnails",
       "Explorer stops generating thumbnails for pictures and video. On a hard drive a photo folder opens instantly instead of loading for seconds, and a weak GPU is spared the previews.",
       "Photos and videos will show generic file-type icons instead of previews."),
      [R("HKCU", ADV, "IconsOnly", "dword", 1, 0)],
      tags=["ui", "disk", "gpu"], logoff=True),

    T("weak.peek-off", "weak", "safe",
      ("Отключить Aero Peek",
       "Предпросмотр рабочего стола при наведении на правый край панели задач и прозрачные рамки окон при наведении на миниатюру. Эффекты считаются диспетчером окон в реальном времени.",
       None),
      ("Disable Aero Peek",
       "The desktop preview when hovering the right end of the taskbar and the transparent window frames on thumbnail hover. Both are computed live by the window manager.",
       None),
      [R("HKCU", ADV, "EnableAeroPeek", "dword", 0, 1),
       R("HKCU", ADV, "DisablePreviewDesktop", "dword", 1, 0),
       R("HKCU", CVU + r"\DWM", "EnableAeroPeek", "dword", 0, 1)],
      tags=["ui", "gpu"], logoff=True),

    T("weak.fth-off", "weak", "advanced",
      ("Отключить отказоустойчивую кучу",
       "Fault Tolerant Heap следит за программами, которые падали из-за работы с памятью, и подменяет им менеджер памяти на более медленный. Со временем список разрастается, и часть старых программ работает медленнее без видимой причины.",
       "Программы, которые раньше падали и лечились этим механизмом, снова могут начать падать."),
      ("Disable the Fault Tolerant Heap",
       "FTH watches programs that crashed on memory operations and swaps in a slower heap manager for them. The list grows over time and some old programs quietly run slower for no visible reason.",
       "Programs that used to crash and were patched up by this mechanism may start crashing again."),
      [R("HKLM", r"SOFTWARE\Microsoft\FTH", "Enabled", "dword", 0, 1)],
      tags=["cpu", "ram"], restart=True),

    T("weak.defender-scan-limit", "weak", "safe",
      ("Ограничить аппетит Защитника при проверке",
       "Плановая проверка Защитника по умолчанию может занимать до половины процессора. Здесь предел снижается до двадцати процентов, а проверка переносится на время простоя. Защита в реальном времени продолжает работать полностью — это не отключение антивируса, а ограничение фоновой проверки.",
       None),
      ("Cap Defender's appetite during scans",
       "A scheduled Defender scan can take up to half the CPU by default. This caps it at twenty percent and moves scans to idle time. Real-time protection keeps working fully — this limits the background scan, it does not disable the antivirus.",
       None),
      [R("HKLM", DEFPOL + r"\Scan", "AvgCPULoadFactor", "dword", 20, 50),
       R("HKLM", DEFPOL + r"\Scan", "ScanOnlyIfIdle", "dword", 1, 0),
       R("HKLM", DEFPOL + r"\Scan", "DisableScanningNetworkFiles", "dword", 1, 0)],
      tags=["cpu"]),

    T("weak.memory-compression-on", "weak", "safe",
      ("Включить сжатие памяти",
       "При малом объёме памяти сжатие страниц спасает от постоянного обращения к файлу подкачки: вместо медленного диска система жмёт страницы в оперативной памяти. На слабой машине это выгодный обмен процессорного времени на скорость.",
       None),
      ("Enable memory compression",
       "With little RAM, page compression saves you from constant page file access: instead of a slow disk the system compresses pages in memory. On a weak machine that is a good trade of CPU time for speed.",
       None),
      [PS("Enable-MMAgent -mc", "Disable-MMAgent -mc")],
      tags=["ram"], req="lowram", restart=True),

    T("weak.discovery-off", "weak", "advanced",
      ("Отключить сетевое обнаружение и датчики",
       "UPnP, обнаружение устройств в сети, служба сканеров и датчиков освещённости. На обычном домашнем компьютере без сетевого принтера и планшетных датчиков они только занимают память и держат открытыми порты.",
       "Сетевые принтеры и медиаустройства DLNA перестанут находиться автоматически."),
      ("Disable network discovery and sensors",
       "UPnP, network device discovery, the scanner service and light sensors. On a plain home PC with no network printer or tablet sensors they only take memory and keep ports open.",
       "Network printers and DLNA media devices will stop being discovered automatically."),
      [SV("SSDPSRV", "disabled", "manual"),
       SV("upnphost", "disabled", "manual"),
       SV("stisvc", "disabled", "manual"),
       SV("AJRouter", "disabled", "manual"),
       SV("SensorService", "disabled", "manual"),
       SV("SensrSvc", "disabled", "manual")],
      tags=["ram", "security"]),

    T("weak.pagefile-managed", "weak", "safe",
      ("Вернуть управление файлом подкачки системе",
       "На машине с малым объёмом памяти отключённый или слишком маленький файл подкачки приводит к вылетам программ с нехваткой памяти. Твик возвращает файл подкачки под управление Windows на системном диске.",
       None),
      ("Let Windows manage the page file",
       "On a low-memory machine a disabled or undersized page file causes out-of-memory crashes. This hands the page file back to Windows on the system drive.",
       None),
      [R("HKLM", MM, "PagingFiles", "multi", "?:\\pagefile.sys", "?:\\pagefile.sys")],
      tags=["ram", "stability"], req="lowram", restart=True),

    T("weak.startup-delay-off", "weak", "safe",
      ("Убрать задержку и анимацию входа",
       "Windows выдерживает паузу перед показом рабочего стола и проигрывает анимацию первого входа. На слабой машине это несколько секунд ожидания при каждом включении.",
       None),
      ("Remove sign-in delay and animation",
       "Windows waits before showing the desktop and plays a first sign-in animation. On a weak machine that is several seconds of waiting at every boot.",
       None),
      [R("HKLM", r"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "EnableFirstLogonAnimation", "dword", 0, 1),
       R("HKCU", CVU + r"\Explorer\Serialize", "StartupDelayInMSec", "dword", 0, 0),
       R("HKLM", CV + r"\Explorer\VisualEffects", "VisualFXSetting", "dword", 2, 0)],
      tags=["boot"]),
]
