from tw_common import *

CLSID = r"Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32"

ITEMS = [
    T("ui.file-extensions", "interface", "safe",
      ("Показывать расширения файлов",
       "Без расширений файл photo.jpg.exe выглядит как обычная картинка. Это самый распространённый способ подсунуть исполняемый файл вместо документа.",
       None),
      ("Show file extensions",
       "Without extensions photo.jpg.exe looks like a picture. This is the most common way to pass off an executable as a document.",
       None),
      [R("HKCU", ADV, "HideFileExt", "dword", 0, 1)],
      tags=["ui", "security"], logoff=True),

    T("ui.hidden-files", "interface", "safe",
      ("Показывать скрытые файлы",
       "Скрытые папки и файлы становятся видны в проводнике. Защищённые системные файлы при этом остаются скрытыми.",
       None),
      ("Show hidden files",
       "Hidden folders and files become visible in Explorer. Protected system files stay hidden.",
       None),
      [R("HKCU", ADV, "Hidden", "dword", 1, 2)],
      tags=["ui"], logoff=True),

    T("ui.classic-context", "interface", "safe",
      ("Классическое контекстное меню",
       "Возвращает полное меню правой кнопки из Windows 10 вместо укороченного меню Windows 11 с пунктом «Показать дополнительные параметры».",
       None),
      ("Classic context menu",
       "Restores the full Windows 10 right-click menu instead of the trimmed Windows 11 one with 'Show more options'.",
       None),
      [R("HKCU", CLSID, "", "sz", "", dk=True)],
      tags=["ui"], req="win11", logoff=True),

    T("ui.taskbar-left", "interface", "safe",
      ("Кнопки панели задач слева",
       "Возвращает выравнивание панели задач по левому краю, как в Windows 10.",
       None),
      ("Taskbar aligned left",
       "Restores the Windows 10 style left-aligned taskbar.",
       None),
      [R("HKCU", ADV, "TaskbarAl", "dword", 0, 1)],
      tags=["ui"], req="win11"),

    T("ui.taskbar-clean", "interface", "safe",
      ("Очистить панель задач",
       "Убирает строку поиска и кнопку представления задач. Поиск остаётся доступен по клавише Windows, а панель задач становится заметно свободнее.",
       None),
      ("Clean up the taskbar",
       "Removes the search box and the task view button. Search stays available on the Windows key and the taskbar gets noticeably roomier.",
       None),
      [R("HKCU", CVU + r"\Search", "SearchboxTaskbarMode", "dword", 0, 1),
       R("HKCU", ADV, "ShowTaskViewButton", "dword", 0, 1)],
      tags=["ui", "ram"], logoff=True),

    T("ui.taskbar-win11", "interface", "safe",
      ("Убрать виджеты и чат с панели задач",
       "Кнопка виджетов с погодой и новостями и кнопка чата Teams. Обе подгружают содержимое из интернета в фоне и держат под это отдельные процессы. Значения существуют только в Windows 11.",
       None),
      ("Remove widgets and chat from the taskbar",
       "The widgets button with weather and news, and the Teams chat button. Both pull content from the internet in the background and keep their own processes. These values exist only on Windows 11.",
       None),
      [R("HKCU", ADV, "TaskbarDa", "dword", 0, 1),
       R("HKCU", ADV, "TaskbarMn", "dword", 0, 1),
       R("HKLM", r"SOFTWARE\Policies\Microsoft\Dsh", "AllowNewsAndInterests", "dword", 0, 1)],
      tags=["ui", "ram"], req="win11", logoff=True),

    T("ui.animations-off", "interface", "advanced",
      ("Отключить анимации окон",
       "Сворачивание, разворачивание и плавное появление окон. На слабой видеокарте и в удалённых сессиях интерфейс сразу становится резче.",
       "Интерфейс станет выглядеть проще: окна будут появляться мгновенно, без плавных переходов."),
      ("Disable window animations",
       "Minimise, maximise and fade animations. On weak GPUs and in remote sessions the interface immediately feels sharper.",
       "The interface looks plainer: windows appear instantly with no transitions."),
      [R("HKCU", r"Control Panel\Desktop\WindowMetrics", "MinAnimate", "sz", "0", "1"),
       R("HKCU", CVU + r"\Explorer\VisualEffects", "VisualFXSetting", "dword", 3, 0),
       R("HKCU", ADV, "TaskbarAnimations", "dword", 0, 1),
       R("HKCU", ADV, "ListviewAlphaSelect", "dword", 0, 1)],
      tags=["ui", "fps"], logoff=True),

    T("ui.transparency-off", "interface", "safe",
      ("Отключить прозрачность",
       "Эффект размытия за панелью задач и меню Пуск считается видеокартой в каждом кадре. На встроенной графике и ноутбуках это заметная экономия.",
       None),
      ("Disable transparency",
       "The blur behind the taskbar and Start menu is computed by the GPU every frame. On integrated graphics and laptops that is a real saving.",
       None),
      [R("HKCU", CVU + r"\Themes\Personalize", "EnableTransparency", "dword", 0, 1)],
      tags=["ui", "fps"]),

    T("ui.dark-mode", "interface", "safe",
      ("Тёмная тема",
       "Тёмное оформление для системы и приложений.",
       None),
      ("Dark theme",
       "Dark appearance for the system and apps.",
       None),
      [R("HKCU", CVU + r"\Themes\Personalize", "AppsUseLightTheme", "dword", 0, 1),
       R("HKCU", CVU + r"\Themes\Personalize", "SystemUsesLightTheme", "dword", 0, 1)],
      tags=["ui"]),

    T("ui.explorer-thispc", "interface", "safe",
      ("Открывать проводник на «Этот компьютер»",
       "Вместо панели быстрого доступа с недавними файлами проводник открывается на списке дисков.",
       None),
      ("Open Explorer on This PC",
       "Explorer opens on the drive list instead of Quick Access with recent files.",
       None),
      [R("HKCU", ADV, "LaunchTo", "dword", 1, 2)],
      tags=["ui"]),

    T("ui.recent-off", "interface", "safe",
      ("Не показывать недавние файлы",
       "Недавние файлы и часто используемые папки перестают отображаться в быстром доступе. Полезно, если компьютером пользуется кто-то ещё.",
       None),
      ("Hide recent files",
       "Recent files and frequent folders stop appearing in Quick Access. Useful if someone else uses the PC.",
       None),
      [R("HKCU", ADV, "ShowRecent", "dword", 0, 1),
       R("HKCU", ADV, "ShowFrequent", "dword", 0, 1),
       R("HKCU", CVU + r"\Policies\Explorer", "NoRecentDocsHistory", "dword", 1, 0)],
      tags=["ui", "privacy"]),

    T("ui.shortcut-suffix-off", "interface", "safe",
      ("Убрать «- ярлык» из имени",
       "Новые ярлыки перестают получать приписку в конце имени.",
       None),
      ("Remove the '- Shortcut' suffix",
       "New shortcuts stop getting the suffix appended to their name.",
       None),
      [R("HKLM", CV + r"\Explorer", "link", "binary", "00000000", "16000000")],
      tags=["ui"], logoff=True),

    T("ui.verbose-status", "interface", "safe",
      ("Подробные сообщения при загрузке",
       "Вместо крутящегося кружка система пишет, что именно она делает при запуске и выключении. Помогает понять, на каком шаге компьютер задумывается.",
       None),
      ("Verbose boot messages",
       "Instead of a spinner the system states what it is doing at startup and shutdown. Helps find where the machine stalls.",
       None),
      [R("HKLM", CV + r"\Policies\System", "VerboseStatus", "dword", 1, 0)],
      tags=["boot"]),

    T("ui.aero-shake-off", "interface", "safe",
      ("Отключить сворачивание встряхиванием",
       "Случайное встряхивание окна мышью больше не будет сворачивать все остальные окна.",
       None),
      ("Disable Aero Shake",
       "Accidentally shaking a window will no longer minimise everything else.",
       None),
      [R("HKCU", ADV, "DisallowShaking", "dword", 1, 0)],
      tags=["ui"]),

    T("ui.sticky-keys-off", "interface", "safe",
      ("Отключить залипание клавиш",
       "Пятикратное нажатие Shift больше не вызывает диалог залипания клавиш. В играх это самое раздражающее всплывающее окно.",
       None),
      ("Disable Sticky Keys",
       "Pressing Shift five times no longer opens the Sticky Keys dialog. The most annoying popup in games.",
       None),
      [R("HKCU", r"Control Panel\Accessibility\StickyKeys", "Flags", "sz", "506", "510"),
       R("HKCU", r"Control Panel\Accessibility\ToggleKeys", "Flags", "sz", "58", "62"),
       R("HKCU", r"Control Panel\Accessibility\Keyboard Response", "Flags", "sz", "122", "126")],
      tags=["input"]),

    T("ui.end-task", "interface", "safe",
      ("«Завершить задачу» в панели задач",
       "Добавляет пункт принудительного завершения прямо в меню правой кнопки на значке программы.",
       None),
      ("End task in the taskbar",
       "Adds a force-quit item directly to the right-click menu of a taskbar icon.",
       None),
      [R("HKCU", ADV + r"\TaskbarDeveloperSettings", "TaskbarEndTask", "dword", 1, 0)],
      tags=["ui"], req="win11"),

    T("ui.compact-view", "interface", "safe",
      ("Компактный вид проводника",
       "Убирает увеличенные отступы между строками в списке файлов.",
       None),
      ("Compact Explorer view",
       "Removes the increased row spacing in the file list.",
       None),
      [R("HKCU", ADV, "UseCompactMode", "dword", 1, 0)],
      tags=["ui"], req="win11", logoff=True),

    T("ui.snap-suggestions-off", "interface", "safe",
      ("Отключить подсказки при прикреплении окон",
       "После прикрепления окна к краю Windows предлагает выбрать соседнее окно. Отключение убирает эту паузу.",
       None),
      ("Disable Snap Assist",
       "After snapping a window Windows offers to pick a neighbour. This removes that pause.",
       None),
      [R("HKCU", ADV, "SnapAssist", "dword", 0, 1),
       R("HKCU", ADV, "EnableSnapAssistFlyout", "dword", 0, 1)],
      tags=["ui"]),

    T("ui.start-recommend-off", "interface", "safe",
      ("Убрать «Рекомендуем» из меню Пуск",
       "Блок с недавними файлами и предлагаемыми приложениями в нижней половине меню Пуск.",
       None),
      ("Hide the Recommended section",
       "The recent files and suggested apps block in the lower half of the Start menu.",
       None),
      [R("HKLM", r"SOFTWARE\Microsoft\PolicyManager\current\device\Start", "HideRecommendedSection", "dword", 1, 0),
       R("HKLM", POL + r"\Explorer", "HideRecommendedSection", "dword", 1, 0),
       R("HKCU", CVU + r"\Explorer\Advanced", "Start_IrisRecommendations", "dword", 0, 1)],
      tags=["ui"], req="win11"),

    T("ui.onedrive-hide", "interface", "safe",
      ("Убрать OneDrive из проводника",
       "Скрывает значок OneDrive из дерева папок. Сам OneDrive не удаляется и продолжает работать, если вы им пользуетесь.",
       None),
      ("Hide OneDrive in Explorer",
       "Hides the OneDrive node in the folder tree. OneDrive itself is not removed and keeps working if you use it.",
       None),
      [R("HKCR", r"CLSID\{018D5C66-4533-4307-9B53-224DE2ED1FE6}", "System.IsPinnedToNameSpaceTree", "dword", 0, 1)],
      tags=["ui"], logoff=True),

    T("svc.legacy-off", "services", "advanced",
      ("Отключить устаревшие службы",
       "Факс, демонстрационный режим для магазинов, сетевой доступ Windows Media Player, родительский контроль, кошелёк, телефония и общий доступ к интернету. На домашнем ПК ни одна из них не используется.",
       "Если вы пользуетесь родительским контролем Microsoft Family или раздаёте интернет через «Мобильный хот-спот», не включайте этот твик."),
      ("Disable legacy services",
       "Fax, retail demo mode, Windows Media Player network sharing, parental controls, wallet, phone service and internet connection sharing. None are used on a home PC.",
       "Skip this if you use Microsoft Family parental controls or the Mobile hotspot."),
      [SV("Fax", "disabled", "manual"),
       SV("RetailDemo", "disabled", "manual"),
       SV("WMPNetworkSvc", "disabled", "manual"),
       SV("WpcMonSvc", "disabled", "manual"),
       SV("WalletService", "disabled", "manual"),
       SV("PhoneSvc", "disabled", "manual"),
       SV("SharedAccess", "disabled", "manual"),
       SV("MapsBroker", "disabled", "auto"),
       SV("TrkWks", "disabled", "auto")],
      tags=["ram"]),

    T("svc.remote-off", "services", "advanced",
      ("Отключить удалённый доступ",
       "Удалённый реестр, удалённый рабочий стол и служба маршрутизации. На домашнем компьютере это только поверхность атаки.",
       "Подключиться к этому компьютеру по RDP или через «Удалённый помощник» станет невозможно."),
      ("Disable remote access",
       "Remote registry, remote desktop and routing services. On a home machine this is only attack surface.",
       "Connecting to this PC over RDP or Remote Assistance becomes impossible."),
      [SV("RemoteRegistry", "disabled", "manual"),
       SV("RemoteAccess", "disabled", "manual"),
       SV("TermService", "disabled", "manual"),
       SV("UmRdpService", "disabled", "manual"),
       SV("SessionEnv", "disabled", "manual")],
      tags=["security"]),

    T("svc.diagnostics-off", "services", "advanced",
      ("Отключить диагностические службы",
       "Служба политики диагностики и узлы диагностики постоянно опрашивают систему и складывают результаты в журналы. Мастер устранения неполадок без них работать не будет.",
       "Встроенные средства устранения неполадок перестанут запускаться."),
      ("Disable diagnostic services",
       "The diagnostic policy service and its hosts constantly poll the system and write logs. The troubleshooting wizards need them.",
       "Built-in troubleshooters will stop working."),
      [SV("DPS", "disabled", "auto"),
       SV("WdiServiceHost", "disabled", "manual"),
       SV("WdiSystemHost", "disabled", "manual"),
       SV("PcaSvc", "disabled", "auto"),
       SV("wercplsupport", "disabled", "manual")],
      tags=["cpu"]),

    T("svc.smartcard-off", "services", "advanced",
      ("Отключить смарт-карты и биометрию",
       "Службы смарт-карт, NFC-платежей и биометрии. Нужны только при входе по отпечатку, лицу или корпоративной карте.",
       "Если вы входите в Windows по отпечатку пальца или через Windows Hello, вход сломается."),
      ("Disable smart cards and biometrics",
       "Smart card, NFC payment and biometric services. Only needed for fingerprint, face or corporate card sign-in.",
       "If you sign in with a fingerprint or Windows Hello, sign-in will break."),
      [SV("SCardSvr", "disabled", "manual"),
       SV("ScDeviceEnum", "disabled", "manual"),
       SV("SEMgrSvc", "disabled", "manual"),
       SV("WbioSrvc", "disabled", "manual")],
      tags=["ram"]),

    T("svc.print-off", "services", "advanced",
      ("Отключить диспетчер печати",
       "Spooler работает всегда, даже если принтера нет. Это ещё и постоянный источник уязвимостей вроде PrintNightmare.",
       "Печать и экспорт в PDF через «Печать в PDF» перестанут работать."),
      ("Disable the print spooler",
       "The spooler runs even with no printer attached and is a recurring source of vulnerabilities like PrintNightmare.",
       "Printing and Print to PDF stop working."),
      [SV("Spooler", "disabled", "auto"),
       SV("PrintNotify", "disabled", "manual")],
      tags=["security", "ram"]),

    T("svc.bluetooth-off", "services", "advanced",
      ("Отключить Bluetooth",
       "Три службы Bluetooth и поддержка беспроводных устройств. Имеет смысл, если в компьютере нет Bluetooth-адаптера или он не используется.",
       "Беспроводные наушники, мыши и геймпады по Bluetooth перестанут подключаться."),
      ("Disable Bluetooth",
       "Three Bluetooth services and wireless device support. Makes sense if there is no adapter or you never use it.",
       "Bluetooth headphones, mice and gamepads will stop connecting."),
      [SV("bthserv", "disabled", "manual"),
       SV("BTAGService", "disabled", "manual"),
       SV("BluetoothUserService", "disabled", "manual")],
      tags=["ram"]),

    T("svc.touch-off", "services", "advanced",
      ("Отключить сенсорный ввод и перо",
       "Служба клавиатуры на экране и панели рукописного ввода. На обычном настольном ПК не нужна.",
       "Экранная клавиатура и ввод пером перестанут работать. На планшетах и ноутбуках с сенсорным экраном включать не стоит."),
      ("Disable touch keyboard and pen",
       "The on-screen keyboard and handwriting panel service. Not needed on a regular desktop.",
       "The touch keyboard and pen input stop working. Do not use on tablets or touchscreen laptops."),
      [SV("TabletInputService", "disabled", "manual")],
      tags=["ram"], req="desktop"),

    T("svc.netdata-off", "services", "advanced",
      ("Отключить учёт сетевого трафика",
       "DusmSvc считает потраченный трафик для лимитных подключений. Служба сидит в сетевом стеке и на части конфигураций добавляет задержку.",
       "Не будет работать: счётчик трафика в «Параметрах» → «Сеть», лимитные подключения и предупреждение о расходе трафика."),
      ("Disable network data usage",
       "DusmSvc counts traffic for metered connections. It sits in the network stack and adds latency on some setups.",
       "Will stop working: the traffic counter in Settings → Network, metered connections and the data usage warning."),
      [SV("DusmSvc", "disabled", "auto")],
      tags=["network", "latency"], src="atlas"),

    T("svc.insider-off", "services", "safe",
      ("Отключить программу предварительной оценки",
       "Служба Windows Insider. Если вы не участвуете в программе предварительных сборок, она не нужна.",
       None),
      ("Disable Windows Insider service",
       "The Windows Insider service. Not needed unless you are on the preview builds.",
       None),
      [SV("wisvc", "disabled", "manual")],
      tags=["ram"]),

    T("app.debloat-bing", "debloat", "safe",
      ("Удалить приложения Bing",
       "Новости, погода, поиск Bing и MSN-виджеты. Именно они возвращают ленту новостей на панель задач после обновлений.",
       None),
      ("Remove Bing apps",
       "News, Weather, Bing Search and MSN widgets. These are what bring the news feed back to the taskbar after updates.",
       None),
      [AX("Microsoft.BingNews"), AX("Microsoft.BingWeather"), AX("Microsoft.BingSearch"),
       AX("Microsoft.BingFinance"), AX("Microsoft.BingSports"), AX("MicrosoftWindows.Client.WebExperience")],
      tags=["ram", "ui"]),

    T("app.debloat-social", "debloat", "safe",
      ("Удалить Teams, Skype и «Связь с телефоном»",
       "Предустановленные коммуникационные приложения, которые стартуют вместе с системой и держат процессы в памяти.",
       "Если вы пользуетесь личным Teams или связью с телефоном Android, не удаляйте."),
      ("Remove Teams, Skype and Phone Link",
       "Preinstalled communication apps that start with the system and keep processes in memory.",
       "Skip if you use personal Teams or Phone Link with Android."),
      [AX("MicrosoftTeams"), AX("MSTeams"), AX("Microsoft.SkypeApp"),
       AX("Microsoft.YourPhone"), AX("Microsoft.People"), AX("Microsoft.Messaging")],
      tags=["ram"]),

    T("app.debloat-media", "debloat", "safe",
      ("Удалить встроенные медиаприложения",
       "Groove Музыка, Кино и ТВ, Clipchamp и Solitaire с подпиской. Полноценные плееры вроде VLC делают то же самое лучше.",
       None),
      ("Remove bundled media apps",
       "Groove Music, Movies & TV, Clipchamp and subscription Solitaire. Real players like VLC do the job better.",
       None),
      [AX("Microsoft.ZuneMusic"), AX("Microsoft.ZuneVideo"), AX("Clipchamp.Clipchamp"),
       AX("Microsoft.MicrosoftSolitaireCollection"), AX("Microsoft.WindowsFeedbackHub"),
       AX("Microsoft.GetHelp"), AX("Microsoft.Getstarted"), AX("Microsoft.MicrosoftOfficeHub"),
       AX("Microsoft.Office.OneNote"), AX("Microsoft.MixedReality.Portal"), AX("Microsoft.3DBuilder")],
      tags=["ram", "disk"]),

    T("app.debloat-xbox", "debloat", "advanced",
      ("Удалить приложения Xbox",
       "Xbox, игровой оверлей и сопутствующие компоненты.",
       "Игры из Game Pass и облачные сохранения Xbox перестанут работать."),
      ("Remove Xbox apps",
       "Xbox, the gaming overlay and related components.",
       "Game Pass titles and Xbox cloud saves will stop working."),
      [AX("Microsoft.XboxApp"), AX("Microsoft.XboxGamingOverlay"), AX("Microsoft.XboxGameOverlay"),
       AX("Microsoft.XboxSpeechToTextOverlay"), AX("Microsoft.GamingApp"), AX("Microsoft.Xbox.TCUI")],
      tags=["ram"]),

    T("app.debloat-ai", "debloat", "safe",
      ("Удалить Copilot и Cortana",
       "Приложения помощников. Политики отключения не удаляют сами пакеты, они остаются на диске и возвращаются после обновлений.",
       None),
      ("Remove Copilot and Cortana",
       "The assistant packages. Disabling policies does not remove them; they stay on disk and return after updates.",
       None),
      [AX("Microsoft.Windows.Ai.Copilot.Provider"), AX("Microsoft.Copilot"),
       AX("Microsoft.549981C3F5F10"), AX("Microsoft.WindowsAlarms")],
      tags=["ram"]),
]
